/* ============================================================================
 * Project Name : ezbox configuration utilities
 * File Name    : nvram/nvram_defaults.c
 *
 * Description  : implement Name-Value RAM default settings
 *
 * Copyright (C) 2008-2014 by ezbox-project
 *
 * History      Rev       Description
 * 2010-08-20   0.1       Write it from scratch
 * ============================================================================
 */

#include "ezcfg-private.h"
#include "ezcfg.h"
#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
#include "ezcfg-ssl.h"
#endif
#if (HAVE_EZBOX_SERVICE_EZCFG_UPNPD == 1)
#include "ezcfg-upnp.h"
#endif

ezcfg_nv_pair_t default_nvram_settings[] = {
	/* System configuration */
	{ NVRAM_SERVICE_OPTION(SYS, DEVICE_NAME), "ezbox" }, /* ezbox */
	{ NVRAM_SERVICE_OPTION(SYS, SERIAL_NUMBER), "012345678901234567" }, /* */
	{ NVRAM_SERVICE_OPTION(SYS, DISTRO_NAME), "kuafu" }, /* kuafu */
	{ NVRAM_SERVICE_OPTION(SYS, HARDWARE_ARCH), "x86_64" }, /* x86_64 */
	{ NVRAM_SERVICE_OPTION(SYS, HARDWARE_VERSION), "1.0" }, /* 1.0 */
	{ NVRAM_SERVICE_OPTION(SYS, SOFTWARE_VERSION), "1.0" }, /* 1.0 */
	{ NVRAM_SERVICE_OPTION(SYS, SOFTWARE_REVISION), "001" }, /* 001 */
	{ NVRAM_SERVICE_OPTION(SYS, HDD_DEVICE), "sda" }, /* sda */
	{ NVRAM_SERVICE_OPTION(SYS, BOOT_ARGS), "boot_dev=sda1,ext4" }, /* sda1,ext4 */

#if 0
	/* system network interfaces, LAN_NIC+WAN_NIC */
	{ NVRAM_SERVICE_OPTION(SYS, NICS), "" },
#if (HAVE_EZBOX_ETH_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, ETH_LAN_NIC), "eth0" },
#endif
#if (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, WIFI_LAN_NIC), "wlan0" },
#endif
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, BR_LAN_NIC), "br-lan" },
#endif
#if (HAVE_EZBOX_LAN_NIC == 1)
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, LAN_NIC), "br-lan" },
#elif (HAVE_EZBOX_ETH_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, LAN_NIC), "eth0" },
#elif (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, LAN_NIC), "wlan0" },
#else
	{ NVRAM_SERVICE_OPTION(SYS, LAN_NIC), "" },
#endif
#endif
#if (HAVE_EZBOX_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(SYS, WAN_NIC), "eth1" },
#endif
#endif

	/* swap device */
	{ NVRAM_SERVICE_OPTION(SYS, SWAP_DEV), "sda5" },
	/* dynamic data storage device */
	{ NVRAM_SERVICE_OPTION(SYS, DATA_DEV), "sda6" },
	/* dynamic data storage device key */
	{ NVRAM_SERVICE_OPTION(SYS, DATA_DEV_KEY), "" },
	/* kernel modules */
	{ NVRAM_SERVICE_OPTION(SYS, MODULES), "" },
#if (HAVE_EZBOX_SERVICE_IPTABLES == 1)
	/* iptables kernel modules */
	{ NVRAM_SERVICE_OPTION(SYS, IPTABLES_MODULES),
		"x_tables," \
		"ip_tables," \
		"iptable_mangle," \
		"iptable_filter," \
		"nf_conntrack," \
		"nf_defrag_ipv4," \
		"nf_conntrack_ipv4," \
		"nf_nat," \
		"iptable_nat," \
		"ipt_MASQUERADE," \
		"xt_state," \
		"xt_tcpudp" },
#endif
	/* LD_LIBRARY_PATH */
	{ NVRAM_SERVICE_OPTION(SYS, LD_LIBRARY_PATH),
#if (HAVE_EZBOX_SERVICE_EMC2 == 1)
		"/usr/realtime/lib,"
#endif
		""
	},

#if 0
	/* NTP */
	{ "ntp_server", "cn.pool.ntp.org hk.pool.ntp.org" }, /* NTP server */
	{ "ntp_mode", "auto" },		/* NTP server mode [manual | auto] */
	{ "ntp_enable", "1" },
	{ "ntp_timezone", "PRC" },

	/* Process Monitor */
	{ "process_monitor_interval", "3" },	/* process_monitor check interval, should be 1-10, default is 3 munites, 0 means not start process_monitor */
	{ "process_monitor_cron_period", "12" },/* cron task for checking process_monitor period, should be 3-30, default is 12 munites, 0 means not setup cron task */
#endif

	/*--------------------*/
	/* EZCFG parameters */
	/*--------------------*/
	{ NVRAM_SERVICE_OPTION(EZCFG, SYS_LANGUAGE), "zh_CN" }, /* zh_CN */
	{ NVRAM_SERVICE_OPTION(EZCFG, SYS_TZ_AREA), "Asia" }, /* Asia */
	{ NVRAM_SERVICE_OPTION(EZCFG, SYS_TZ_LOCATION), "Shanghai" }, /* Shanghai */
	{ NVRAM_SERVICE_OPTION(EZCFG, SYS_RESTORE_DEFAULTS), "0" }, /* Set to 0 not restore defaults on boot */

	/* EZCFG common log level */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_LOG_LEVEL),
	  EZCFG_COMMON_LOG_LEVEL_ERR_STRING }, /* err | info | debug */
	/* EZCFG common rules path */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_RULES_PATH),
	  EZCFG_COMMON_DEFAULT_RULES_PATH },
	/* EZCFG common sem ezcfg path */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SEM_EZCFG_PATH),
	  EZCFG_SEM_EZCFG_PATH },
	/* EZCFG common ctrl socket path */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SOCK_CTRL_PATH),
	  EZCFG_SOCK_CTRL_PATH },
	/* EZCFG common nvram socket path */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SOCK_NVRAM_PATH),
	  EZCFG_SOCK_NVRAM_PATH },
	/* EZCFG common uevent socket path */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SOCK_UEVENT_PATH),
	  EZCFG_SOCK_UEVENT_PATH },
	/* EZCFG common socket number */
#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SOCKET_NUMBER), "2" },
#else
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SOCKET_NUMBER), "1" },
#endif
	/* EZCFG common locale */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_LOCALE),
	  EZCFG_COMMON_DEFAULT_LOCALE_STRING },
	/* EZCFG common authentication number */
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_AUTH_NUMBER), "1" },
	/* EZCFG common SSL number */
#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_SSL_NUMBER), "1" },
#endif
	/* EZCFG common IGRS number */
#if (HAVE_EZBOX_SERVICE_EZCFG_IGRS == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_IGRS_NUMBER), "1" },
#endif
	/* EZCFG common UPnP number */
#if (HAVE_EZBOX_SERVICE_EZCFG_UPNPD == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, COMMON_UPNP_NUMBER), "2" },
#endif
	/* EZCFG NVRAM buffer size */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_0_BUFFER_SIZE),
	  EZCFG_NVRAM_BUFFER_SIZE_STRING },
	/* EZCFG NVRAM backend type */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_0_BACKEND_TYPE),
	  EZCFG_NVRAM_BACKEND_FILE_STRING }, /* 0: none, 1: file, 2: flash, 3: hdd */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_0_CODING_TYPE),
	  EZCFG_NVRAM_CODING_NONE_STRING }, /* 0: none, 1: gzip */
	/* EZCFG NVRAM storage path */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_0_STORAGE_PATH),
	  EZCFG_NVRAM_STORAGE_PATH },
#if (1 < EZCFG_NVRAM_STORAGE_NUM)
	/* EZCFG NVRAM buffer size */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_1_BUFFER_SIZE),
	  EZCFG_NVRAM_BUFFER_SIZE_STRING },
	/* EZCFG NVRAM backend type */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_1_BACKEND_TYPE),
	  EZCFG_NVRAM_BACKEND_FILE_STRING }, /* 0: none, 1: file, 2: flash, 3: hdd */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_1_CODING_TYPE),
	  EZCFG_NVRAM_CODING_NONE_STRING }, /* 0: none, 1: gzip */
	/* EZCFG NVRAM storage path */
	{ NVRAM_SERVICE_OPTION(EZCFG, NVRAM_1_STORAGE_PATH),
	  EZCFG_NVRAM_BACKUP_STORAGE_PATH },
#endif
	/* EZCFG socket domain */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_0_DOMAIN),
	  EZCFG_SOCKET_DOMAIN_INET_STRING },
	/* EZCFG socket type */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_0_TYPE),
	  EZCFG_SOCKET_TYPE_STREAM_STRING },
	/* EZCFG socket protocol */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_0_PROTOCOL),
	  EZCFG_SOCKET_PROTO_HTTP_STRING },
	/* EZCFG socket address */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_0_ADDRESS),
	  EZCFG_LOOPBACK_DEFAULT_IPADDR
	  ":" EZCFG_PROTO_HTTP_PORT_NUMBER_STRING },
#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
	/* EZCFG socket domain */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_1_DOMAIN),
	  EZCFG_SOCKET_DOMAIN_INET_STRING },
	/* EZCFG socket type */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_1_TYPE),
	  EZCFG_SOCKET_TYPE_STREAM_STRING },
	/* EZCFG socket protocol */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_1_PROTOCOL),
	  EZCFG_SOCKET_PROTO_HTTPS_STRING },
	/* EZCFG socket address */
	{ NVRAM_SERVICE_OPTION(EZCFG, SOCKET_1_ADDRESS),
	  EZCFG_LOOPBACK_DEFAULT_IPADDR
	  ":" EZCFG_PROTO_HTTPS_PORT_NUMBER_STRING },
#endif

	/* EZCFG authentication type */
	{ NVRAM_SERVICE_OPTION(EZCFG, AUTH_0_TYPE),
	  EZCFG_AUTH_TYPE_HTTP_BASIC_STRING },
	/* EZCFG authentication username */
	{ NVRAM_SERVICE_OPTION(EZCFG, AUTH_0_USER),
	  EZCFG_AUTH_USER_ADMIN_STRING },
	/* EZCFG authentication realm */
	{ NVRAM_SERVICE_OPTION(EZCFG, AUTH_0_REALM),
	  EZCFG_AUTH_REALM_ADMIN_STRING },
	/* EZCFG authentication domain */
	{ NVRAM_SERVICE_OPTION(EZCFG, AUTH_0_DOMAIN),
	  EZCFG_AUTH_DOMAIN_ADMIN_STRING },
	/* EZCFG authentication secret */
	{ NVRAM_SERVICE_OPTION(EZCFG, AUTH_0_SECRET),
	  EZCFG_AUTH_SECRET_ADMIN_STRING },

#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
	/* EZCFG SSL role */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_ROLE), EZCFG_SSL_ROLE_SERVER_STRING },
	/* EZCFG SSL method */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_METHOD),
	  EZCFG_SSL_METHOD_SSLV23_STRING },
	/* EZCFG SSL socket enable */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_SOCKET_ENABLE), "1" },
	/* EZCFG SSL socket domain */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_SOCKET_DOMAIN),
	  EZCFG_SOCKET_DOMAIN_INET_STRING },
	/* EZCFG SSL socket type */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_SOCKET_TYPE),
	  EZCFG_SOCKET_TYPE_STREAM_STRING },
	/* EZCFG SSL socket protocol */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_SOCKET_PROTOCOL),
	  EZCFG_SOCKET_PROTO_HTTPS_STRING },
	/* EZCFG SSL socket address */
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_SOCKET_ADDRESS),
	  EZCFG_LOOPBACK_DEFAULT_IPADDR
	  ":" EZCFG_PROTO_HTTPS_PORT_NUMBER_STRING },
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_CERTIFICATE_FILE), EZCFG_SSL_CERT_ROOT_PATH "/ezcfg_httpd.cert.pem" },
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_CERTIFICATE_CHAIN_FILE), "" },
	{ NVRAM_SERVICE_OPTION(EZCFG, SSL_0_PRIVATE_KEY_FILE), EZCFG_SSL_PRIV_ROOT_PATH "/ezcfg_httpd.key.pem" },
#endif

#if (HAVE_EZBOX_SERVICE_EZCFG_UPNPD == 1)
	/* EZCFG UPnP role */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_0_ROLE), EZCFG_UPNP_ROLE_DEVICE_STRING },
	/* EZCFG UPnP device type */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_0_DEVICE_TYPE),
	  EZCFG_UPNP_DEV_TYPE_IGD1_STRING },
	/* EZCFG UPnP root device description */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_0_DESCRIPTION_PATH),
	  EZCFG_UPNP_IGD1_ROOT_DEVICE_XML_FILE },
	/* EZCFG UPnP binding interfaces */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_0_INTERFACE),
#if (HAVE_EZBOX_LAN_NIC == 1)
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	  "br-lan"
#elif (HAVE_EZBOX_ETH_LAN_NIC == 1)
	  "eth0"
#elif (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	  "wlan0"
#else
	  ""
#endif
#else
	  "eth1"
#endif
	},

	/* EZCFG UPnP role */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_1_ROLE), EZCFG_UPNP_ROLE_CONTROL_POINT_STRING },
	/* EZCFG UPnP device type */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_1_DEVICE_TYPE),
	  EZCFG_UPNP_DEV_TYPE_IGD1_STRING },
	/* EZCFG UPnP root device description */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_1_DESCRIPTION_PATH),
	  EZCFG_UPNP_IGD1_ROOT_DEVICE_XML_FILE },
	/* EZCFG UPnP binding interfaces */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNP_1_INTERFACE),
#if (HAVE_EZBOX_LAN_NIC == 1)
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	  "br-lan"
#elif (HAVE_EZBOX_ETH_LAN_NIC == 1)
	  "eth0"
#elif (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	  "wlan0"
#else
	  ""
#endif
#else
	  "eth1"
#endif
	},
#endif

	/* ezcfg HTTP server [1|0] */
	{ NVRAM_SERVICE_OPTION(EZCFG, HTTPD_ENABLE), "1" },
	/* Support HTTP protocol */
	{ NVRAM_SERVICE_OPTION(EZCFG, HTTPD_HTTP), "1" },
#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
	/* Support HTTPS protocol */
	{ NVRAM_SERVICE_OPTION(EZCFG, HTTPD_HTTPS), "1" },
#endif
	/* ezcfg HTTP server binding interface */
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, HTTPD_BINDING), "lan" },
#else
	{ NVRAM_SERVICE_OPTION(EZCFG, HTTPD_BINDING), "wan" },
#endif

#if (HAVE_EZBOX_SERVICE_EZCFG_IGRSD == 1)
	/* ezcfg IGRS server [1|0] */
	{ NVRAM_SERVICE_OPTION(EZCFG, IGRSD_ENABLE), "1" },
	/* ezcfg UPnP server binding interface */
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, IGRSD_BINDING), "lan" },
#else
	{ NVRAM_SERVICE_OPTION(EZCFG, IGRSD_BINDING), "wan" },
#endif
#endif

#if (HAVE_EZBOX_SERVICE_EZCFG_UPNPD == 1)
	/* ezcfg UPnP server [1|0] */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNPD_ENABLE), "1" },
	/* ezcfg UPnP server binding interface */
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNPD_BINDING), "lan" },
#else
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNPD_BINDING), "wan" },
#endif
#if (HAVE_EZBOX_SERVICE_EZCFG_UPNPD_IGD1 == 1)
	/* ezcfg UPnP IGD1 device [1|0] */
	{ NVRAM_SERVICE_OPTION(EZCFG, UPNPD_IGD1_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_DESCRIPTION_PATH),
	  EZCFG_UPNP_IGD1_ROOT_DEVICE_XML_FILE },
	/* IGD root device */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_FRIENDLY_NAME),
	  "ezbox Internet Gateway Device" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_MANUFACTURER),
	  "ezbox Project" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_MANUFACTURER_URL),
	  "http://code.google.com/p/ezbox/" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_MODEL_DESCRIPTION),
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_MODEL_NAME),
	  "ezbox IGD Version 1.00" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_MODEL_NUMBER),
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_MODEL_URL),
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERIAL_NUMBER),
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_UDN),
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_ICON_NUMBER),
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_ICON) ".1." \
		EZCFG_UPNP_DESC_MIME_TYPE_ELEMENT_NAME,
	  "image/gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_ICON) ".1." \
		EZCFG_UPNP_DESC_WIDTH_ELEMENT_NAME,
	  "118" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_ICON) ".1." \
		EZCFG_UPNP_DESC_HEIGHT_ELEMENT_NAME,
	  "119" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_ICON) ".1." \
		EZCFG_UPNP_DESC_DEPTH_ELEMENT_NAME,
	  "8" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_ICON) ".1." \
		EZCFG_UPNP_DESC_URL_ELEMENT_NAME,
	  "/igd.gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERVICE_NUMBER),
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERVICE) ".1." \
		EZCFG_UPNP_DESC_SERVICE_TYPE_ELEMENT_NAME,
	  "urn:schemas-upnp-org:service:Layer3Forwarding:1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERVICE) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ID_ELEMENT_NAME,
	  "urn:upnp-org:serviceId:Layer3Forwarding1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERVICE) ".1." \
		EZCFG_UPNP_DESC_SCPD_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/service/Layer3Forwarding1.xml" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERVICE) ".1." \
		EZCFG_UPNP_DESC_CONTROL_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/control?Layer3Forwarding1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_IGD_SERVICE) ".1." \
		EZCFG_UPNP_DESC_EVENT_SUB_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/event?Layer3Forwarding1" },
	/* IGD WANDevice */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND_NUMBER),
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_FRIENDLY_NAME_ELEMENT_NAME,
	  "WANDevice" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_MANUFACTURER_ELEMENT_NAME,
	  "ezbox Project" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_MANUFACTURER_URL_ELEMENT_NAME,
	  "http://code.google.com/p/ezbox/" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_DESCRIPTION_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_NAME_ELEMENT_NAME,
	  "ezbox IGD Version 1.00" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_NUMBER_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_URL_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_SERIAL_NUMBER_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_UDN_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_ICON_NUMBER_STRING,
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_MIME_TYPE_ELEMENT_NAME,
	  "image/gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_WIDTH_ELEMENT_NAME,
	  "118" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_HEIGHT_ELEMENT_NAME,
	  "119" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_DEPTH_ELEMENT_NAME,
	  "8" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_URL_ELEMENT_NAME,
	  "/igd.gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_SERVICE_NUMBER_STRING,
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SERVICE_TYPE_ELEMENT_NAME,
	  "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SERVICE_ID_ELEMENT_NAME,
	  "urn:upnp-org:serviceId:WANCommonIFC1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SCPD_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/service/WANCommonInterfaceConfig1.xml" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_CONTROL_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/control?WANCommonIFC1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_EVENT_SUB_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/event?WANCommonIFC1" },
	/* IGD WANConnectionDevice */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WANCD_NUMBER_STRING,
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_FRIENDLY_NAME_ELEMENT_NAME,
	  "WANConnectionDevice" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_MANUFACTURER_ELEMENT_NAME,
	  "ezbox Project" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_MANUFACTURER_URL_ELEMENT_NAME,
	  "http://code.google.com/p/ezbox/" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_MODEL_DESCRIPTION_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_MODEL_NAME_ELEMENT_NAME,
	  "ezbox IGD Version 1.00" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_MODEL_NUMBER_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_MODEL_URL_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERIAL_NUMBER_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_UDN_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_ICON_NUMBER_STRING,
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_MIME_TYPE_ELEMENT_NAME,
	  "image/gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_WIDTH_ELEMENT_NAME,
	  "118" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_HEIGHT_ELEMENT_NAME,
	  "119" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_DEPTH_ELEMENT_NAME,
	  "8" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_URL_ELEMENT_NAME,
	  "/igd.gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_SERVICE_NUMBER_STRING,
	  "3" },
	/* WANEthernetConnection */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SERVICE_TYPE_ELEMENT_NAME,
	  "urn:schemas-upnp-org:service:WANEthernetLinkConfig:1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SERVICE_ID_ELEMENT_NAME,
	  "urn:upnp-org:serviceId:WANEthernetLinkCfg1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SCPD_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/service/WANEthernetLinkConfig1.xml" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_CONTROL_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/control?WANEthernetLinkCfg1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_EVENT_SUB_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/event?WANEthernetLinkCfg1" },
	/* WANPPPConnection */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".2." \
		EZCFG_UPNP_DESC_SERVICE_TYPE_ELEMENT_NAME,
	  "urn:schemas-upnp-org:service:WANPPPConnection:1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".2." \
		EZCFG_UPNP_DESC_SERVICE_ID_ELEMENT_NAME,
	  "urn:upnp-org:serviceId:WANPPPConn1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".2." \
		EZCFG_UPNP_DESC_SCPD_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/service/WANPPPConnection1.xml" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".2." \
		EZCFG_UPNP_DESC_CONTROL_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/control?WANPPPConn1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".2." \
		EZCFG_UPNP_DESC_EVENT_SUB_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/event?WANPPPConn1" },
	/* WANIPConnection */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".3." \
		EZCFG_UPNP_DESC_SERVICE_TYPE_ELEMENT_NAME,
	  "urn:schemas-upnp-org:service:WANIPConnection:1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".3." \
		EZCFG_UPNP_DESC_SERVICE_ID_ELEMENT_NAME,
	  "urn:upnp-org:serviceId:WANIPConn1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".3." \
		EZCFG_UPNP_DESC_SCPD_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/service/WANIPConnection1.xml" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".3." \
		EZCFG_UPNP_DESC_CONTROL_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/control?WANIPConn1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_WAND) ".1." \
		EZCFG_UPNP_WAN_CONNECTION_DEVCIE_STRING ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".3." \
		EZCFG_UPNP_DESC_EVENT_SUB_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/event?WANIPConn1" },
	/* IGD LANDevice */
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND_NUMBER),
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_FRIENDLY_NAME_ELEMENT_NAME,
	  "LANDevice" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_MANUFACTURER_ELEMENT_NAME,
	  "ezbox Project" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_MANUFACTURER_URL_ELEMENT_NAME,
	  "http://code.google.com/p/ezbox/" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_DESCRIPTION_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_NAME_ELEMENT_NAME,
	  "ezbox IGD Version 1.00" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_NUMBER_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_MODEL_URL_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_SERIAL_NUMBER_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_UDN_ELEMENT_NAME,
	  "" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_ICON_NUMBER_STRING,
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_MIME_TYPE_ELEMENT_NAME,
	  "image/gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_WIDTH_ELEMENT_NAME,
	  "118" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_HEIGHT_ELEMENT_NAME,
	  "119" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_DEPTH_ELEMENT_NAME,
	  "8" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_ICON_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_URL_ELEMENT_NAME,
	  "/igd.gif" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_SERVICE_NUMBER_STRING,
	  "1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SERVICE_TYPE_ELEMENT_NAME,
	  "urn:schemas-upnp-org:service:LANHostConfigManagement:1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SERVICE_ID_ELEMENT_NAME,
	  "urn:upnp-org:serviceId:LANHostCfg1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_SCPD_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/service/LANHostConfigManagement1.xml" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_CONTROL_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/control?LANHostCfg1" },
	{ NVRAM_SERVICE_OPTION(UPNP, IGD1_LAND) ".1." \
		EZCFG_UPNP_DESC_SERVICE_ELEMENT_NAME ".1." \
		EZCFG_UPNP_DESC_EVENT_SUB_URL_ELEMENT_NAME,
	  "/" EZCFG_UPNP_DEV_TYPE_IGD1_STRING "/event?LANHostCfg1" },
#endif
#endif

	/*--------------------*/
	/* Loopback H/W parameters */
	/*--------------------*/
	/* Loopback interface name */
	{ NVRAM_SERVICE_OPTION(LOOPBACK, IFNAME), "lo" },

	/* Loopback TCP/IP parameters */
	/* Loopback IP address */
	{ NVRAM_SERVICE_OPTION(LOOPBACK, IPADDR),
	  EZCFG_LOOPBACK_DEFAULT_IPADDR },
	/* Loopback netmask */
	{ NVRAM_SERVICE_OPTION(LOOPBACK, NETMASK),
	  EZCFG_LOOPBACK_DEFAULT_NETMASK },

#if (HAVE_EZBOX_ETH_LAN_NIC == 1)
	/* EtherLAN interface name */
	{ NVRAM_SERVICE_OPTION(ETH_LAN, IFNAME), "eth0" },
	/* EtherLAN driver names (e.g. 8139too) */
	{ NVRAM_SERVICE_OPTION(ETH_LAN, HWNAME), "" },
	/* EtherLAN PHY port mode [auto|10half|10full|100half|100full|1000full] */
	{ NVRAM_SERVICE_OPTION(ETH_LAN, PHYMODE), "auto" },
#endif

#if (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	/* WifiLAN interface name */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, IFNAME), "wlan0" },
	/* WifiLAN driver names (e.g. rt73usb) */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, HWNAME), "" },
	/* WifiLAN PHY port mode [a|bg|an|bgn|abgn|ac] */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, PHYMODE), "bgn" },
#endif

#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	/*--------------------*/
	/* LAN bridge H/W parameters */
	/*--------------------*/
	/* LAN bridge name */
	{ NVRAM_SERVICE_OPTION(BR_LAN, IFNAME), "br-lan" },
	/* LAN bridge included interfaces' name */
	{ NVRAM_SERVICE_OPTION(BR_LAN, IFNAMES), "eth0 wlan0" },
#endif

#if (HAVE_EZBOX_LAN_NIC == 1)
	/*--------------------*/
	/* LAN H/W parameters */
	/*--------------------*/
	/* LAN interface name */
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(LAN, IFNAME), "br-lan" },
#elif (HAVE_EZBOX_ETH_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(LAN, IFNAME), "eth0" },
#elif (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(LAN, IFNAME), "wlan0" },
#else
	{ NVRAM_SERVICE_OPTION(LAN, IFNAME), "" },
#endif
	/* LAN interface MAC address */
	{ NVRAM_SERVICE_OPTION(LAN, HWADDR), "" },

	/* LAN TCP/IP parameters */
	/* LAN IP address */
	{ NVRAM_SERVICE_OPTION(LAN, IPADDR),
	  EZCFG_LAN_DEFAULT_IPADDR },
	/* LAN netmask */
	{ NVRAM_SERVICE_OPTION(LAN, NETMASK),
	  EZCFG_LAN_DEFAULT_NETMASK },
	/* LAN gateway */
	{ NVRAM_SERVICE_OPTION(LAN, GATEWAY),
	  EZCFG_LAN_DEFAULT_GATEWAY },
	/* LAN side WINS server ip list [x.x.x.x x.x.x.x ...] */
	{ NVRAM_SERVICE_OPTION(LAN, WINS), "" },
	/* LAN domain name */
	{ NVRAM_SERVICE_OPTION(LAN, DOMAIN), "" },
	/* LAN spanning tree protocol */
	{ NVRAM_SERVICE_OPTION(LAN, STP_ENABLE), "0" },
#endif

#if (HAVE_EZBOX_ETH_WAN_NIC == 1)
	/* EtherWAN interface name */
	{ NVRAM_SERVICE_OPTION(ETH_WAN, IFNAME), "eth1" },
	/* EtherWAN driver name (e.g. 8139cp) */
	{ NVRAM_SERVICE_OPTION(ETH_WAN, HWNAME), "" },
	/* EtherWAN PHY port mode [auto|10half|10full|100half|100full|1000full] */
	{ NVRAM_SERVICE_OPTION(ETH_WAN, PHYMODE), "auto" },
#endif

#if (HAVE_EZBOX_ADLS_WAN_NIC == 1)
	/* ADSL WAN interface name */
	{ NVRAM_SERVICE_OPTION(ADSL_WAN, IFNAME), "nas0" },
#endif

#if (HAVE_EZBOX_VDLS_WAN_NIC == 1)
	/* VDSL WAN interface name */
	{ NVRAM_SERVICE_OPTION(VDSL_WAN, IFNAME), "ptm0" },
#endif

#if (HAVE_EZBOX_WIFI_WAN_NIC == 1)
	/* WifiWAN interface name */
	{ NVRAM_SERVICE_OPTION(WIFI_WAN, IFNAME), "wlan1" },
	/* WifiWAN driver name (e.g. rt73usb) */
	{ NVRAM_SERVICE_OPTION(WIFI_WAN, HWNAME), "" },
	/* WifiWAN PHY port mode [a|bg|an|bgn|abgn|ac] */
	{ NVRAM_SERVICE_OPTION(WIFI_WAN, PHYMODE), "bgn" },
#endif

#if (HAVE_EZBOX_WAN_NIC == 1)
	/* WAN H/W parameters */
	/* WAN interface name */
#if (HAVE_EZBOX_ETH_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(WAN, IFNAME), "eth1" },
#elif (HAVE_EZBOX_ADSL_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(WAN, IFNAME), "nas0" },
#elif (HAVE_EZBOX_VDSL_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(WAN, IFNAME), "ptm0" },
#elif (HAVE_EZBOX_WIFI_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(WAN, IFNAME), "wlan1" },
#else
	{ NVRAM_SERVICE_OPTION(WAN, IFNAME), "" },
#endif
	/* WAN interface MAC address */
	{ NVRAM_SERVICE_OPTION(WAN, HWADDR), "" },
	/* WAN interface MAC clone [0|1] */
	{ NVRAM_SERVICE_OPTION(WAN, MACCLONE_ENABLE), "0" },
	/* WAN interface MAC clone address */
	{ NVRAM_SERVICE_OPTION(WAN, CLONE_HWADDR), "" },

        /* WAN TCP/IP parameters */
	/* WAN connection type [dhcp|static|pppoe|disabled] */
	{ NVRAM_SERVICE_OPTION(WAN, TYPE), "dhcp" },
	/* WAN connection release [1|0] */
	{ NVRAM_SERVICE_OPTION(WAN, RELEASE), "0" },
	/* WAN hostname */
	{ NVRAM_SERVICE_OPTION(WAN, HOSTNAME), "" },
	/* WAN MTU setting mode [1|0] */
	{ NVRAM_SERVICE_OPTION(WAN, MTU_ENABLE), "0" },
	/* Negotiate MTU to the smaller of this value or the peer MRU */
	{ NVRAM_SERVICE_OPTION(WAN, MTU), "1500" },

	/* WAN static IP parameters */
	/* WAN interface */
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_IFNAME), "eth1" },
	/* WAN IP address */
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_IPADDR), "0.0.0.0" },
	/* WAN netmask */
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_NETMASK), "0.0.0.0" },
	/* WAN gateway */
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_GATEWAY), "0.0.0.0" },
	/* WAN DNS server IP address */
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_DNS1), "" },
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_DNS2), "" },
	{ NVRAM_SERVICE_OPTION(WAN, STATIC_DNS3), "" },

	/* WAN DHCP Client parameters */
	/* WAN interface */
	{ NVRAM_SERVICE_OPTION(WAN, DHCP_IFNAME), "eth1" },
	/* WAN DHCP gateway set enable [0|1] */
	{ NVRAM_SERVICE_OPTION(WAN, DHCP_GATEWAY_ENABLE), "0" },
	/* WAN DHCP gateway MAC address */
	{ NVRAM_SERVICE_OPTION(WAN, DHCP_GATEWAY_MAC), "FF:FF:FF:FF:FF:FF" },
	/* WAN WINS server IP address [x.x.x.x x.x.x.x ...] */
	{ NVRAM_SERVICE_OPTION(WAN, DHCP_WINS), "" },


	/* PPPoE parameters */
#if (HAVE_EZBOX_WAN_PPPOE == 1)
	/* PPPoE PHY interface */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_DEVICE_NAME), "eth1" },
	/* PPPoE enslaved interface */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_IFNAME), "ppp0" },
	/* Restore link automatically [0|1] */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_KEEP_ENABLE), "1" },
	/* PPP options file name */
#if (HAVE_EZBOX_SERVICE_PPP_RP_PPPOE == 1)
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_PPP_OPTIONS_FILE), "/etc/ppp/rp-pppoe-options" },
#endif
	/* PPP username */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_PPP_USERNAME), "" },
	/* PPP password */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_PPP_PASSWD), "" },
	/* Dial on demand max idle time (seconds) */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_PPP_IDLE), "60" },
	/* PPP Redial Period (seconds) */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_PPP_LCP_ECHO_INTERVAL), "60" },
	/* PPP Redial Failure (times) */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_PPP_LCP_ECHO_FAILURE), "3" },
	/* Negotiate MRU to this value */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_MRU), "1492" },
	/* Negotiate MTU to the smaller of this value or the peer MRU */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_MTU), "1492" },
	/* PPPoE service name */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_SERVICE), "" },
	/* PPPoE access concentrator name */
	{ NVRAM_SERVICE_OPTION(WAN, PPPOE_ACNAME), "" },
#endif

	/* PPTP parameters */
#if (HAVE_EZBOX_WAN_PPTP == 1)
	/* PPTP enslaved interface */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_IFNAME), "ppp0" },
	/* PPTP assigned IP address */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_IPADDR), "0.0.0.0" },
	/* PPTP assigned netmask */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_NETMASK), "0.0.0.0" },
	/* PPTP assigned gateway */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_GATEWAY), "0.0.0.0" },
	/* PPTP DNS server IP address */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_DNS1), "" },
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_DNS2), "" },
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_DNS3), "" },
	/* PPTP server IP address */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_SERVER_IPADDR), "0.0.0.0" },
	/* Restore link automatically */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_KEEP_ENABLE), "1" },
	/* PPP username */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_PPP_USERNAME), "" },
	/* PPP password */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_PPP_PASSWD), "" },
	/* Dial on demand max idle time (seconds) */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_PPP_IDLE), "60" },
	/* PPP Redial Period  (seconds)*/
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_PPP_LCP_ECHO_INTERVAL), "60" },
	/* PPP Redial Failure  (times) */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_PPP_LCP_ECHO_FAILURE), "3" },
	/* Negotiate MRU to this value */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_MRU), "1460" },
	/* Negotiate MTU to the smaller of this value or the peer MRU */
	{ NVRAM_SERVICE_OPTION(WAN, PPTP_MTU), "1460" },
#endif

	/* L2TP parameters */
#if (HAVE_EZBOX_WAN_L2TP == 1)
	/* L2TP enslaved interface */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_IFNAME), "ppp0" },
	/* L2TP server IP address */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_SERVER_IPADDR), "0.0.0.0" },
	/* Restore link automatically */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_KEEP_ENABLE), "1" },
	/* PPP username */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_PPP_USERNAME), "" },
	/* PPP password */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_PPP_PASSWD), "" },
	/* Dial on demand max idle time (seconds) */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_PPP_IDLE), "60" },
	/* PPP Redial Period  (seconds) */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_PPP_LCP_ECHO_INTERVAL), "60" },
	/* PPP Redial Failure  (times) */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_PPP_LCP_ECHO_FAILURE), "3" },
	/* Negotiate MRU to this value */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_MRU), "1460" },
	/* Negotiate MTU to the smaller of this value or the peer MRU */
	{ NVRAM_SERVICE_OPTION(WAN, L2TP_MTU), "1460" },
#endif
#endif

#if (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	/*--------------------*/
	/* WifiLAN H/W parameters */
	/*--------------------*/
	/* WifiLAN driver names (e.g. rt87usb) */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, HWNAME), "" },
	/* WifiLAN interface MAC address */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, HWADDR), "" },
	/* WifiLAN PHY mode [auto] */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, PHYMODE), "auto" },
	/* WifiLAN node type [ap|sta|mp|map] */
	{ NVRAM_SERVICE_OPTION(WIFI_LAN, NODE_TYPE), "sta" },
#endif

#if (HAVE_EZBOX_SERVICE_WPA_SUPPLICANT == 1)
	/* hostapd wpa_supplicant related options */
	{ NVRAM_SERVICE_OPTION(RC, WPA_SUPPLICANT_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, CTRL_INTERFACE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, EAPOL_VERSION), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, AP_SCAN), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, FAST_REAUTH), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, DRIVER_PARAM), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, COUNTRY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, DOT11_RSNA_CONFIG_PMK_LIFETIME), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, DOT11_RSNA_CONFIG_PMK_REAUTH_THRESHOLD), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, DOT11_RSNA_CONFIG_SA_TIMEOUT), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, UUID), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, DEVICE_NAME), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, MANUFACTURER), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, MODEL_NAME), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, MODEL_NUMBER), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, SERIAL_NUMBER), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, DEVICE_TYPE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, OS_VERSION), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, CONFIG_METHODS), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, WPS_CRED_PROCESSING), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, BSS_MAX_COUNT), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, FILTER_SSIDS), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_DISABLED), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_ID_STR), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_SSID), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_SCAN_SSID), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_BSSID), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PRIORITY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_MODE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_FREQUENCY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_SCAN_FREQ), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_FREQ_LIST), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PROTO), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_KEY_MGMT), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_AUTH_ALG), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PAIRWISE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_GROUP), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PSK), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_EAPOL_FLAGS), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_MIXED_CELL), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PROACTIVE_KEY_CACHING), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_WEP_KEY0), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_WEP_KEY1), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_WEP_KEY2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_WEP_KEY3), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_WEP_TX_KEYIDX), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PEERKEY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_WPA_PTK_REKEY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_EAP), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_IDENTITY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_ANONYMOUS_IDENTITY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PASSWORD), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_CA_CERT), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_CA_PATH), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_CLIENT_CERT), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PRIVATE_KEY), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PRIVATE_KEY_PASSWD), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_DH_FILE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_SUBJECT_MATCH), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_ALTSUBJECT_MATCH), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PHASE1), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PHASE2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_CA_CERT2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_CA_PATH2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_CLIENT_CERT2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PRIVATE_KEY2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PRIVATE_KEY2_PASSWD), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_DH_FILE2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_SUBJECT_MATCH2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_ALTSUBJECT_MATCH2), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_FRAGMENT_SIZE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_PAC_FILE), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_FAST_MAX_PAC_LIST_LEN), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_FAST_PAC_FORMAT), "" },
	{ NVRAM_SERVICE_OPTION(WPA_SUPPLICANT, NETWORK_EAP_WORKAROUND), "" },
#endif

	/* rc services controller */
#if (HAVE_EZBOX_SERVICE_SYSLOGD == 1)
	/* syslog enabled */
	{ NVRAM_SERVICE_OPTION(RC, SYSLOGD_ENABLE), "1" },
#endif

#if (HAVE_EZBOX_SERVICE_KLOGD == 1)
	/* klog enabled */
	{ NVRAM_SERVICE_OPTION(RC, KLOGD_ENABLE), "1" },
#endif

#if (HAVE_EZBOX_SERVICE_OPENSSL == 1)
	/* openssl enabled */
	{ NVRAM_SERVICE_OPTION(RC, OPENSSL_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(OPENSSL, HOME), EZCFG_SSL_CONF_ROOT_PATH },
	{ NVRAM_SERVICE_OPTION(OPENSSL, RANDFILE), EZCFG_SSL_CONF_ROOT_PATH "/.rnd" },
	{ NVRAM_SERVICE_OPTION(OPENSSL, OID_FILE), EZCFG_SSL_CONF_ROOT_PATH "/.oid" },
	{ NVRAM_SERVICE_OPTION(OPENSSL, OID_SECTION), "new_oids" },
#endif

#if (HAVE_EZBOX_SERVICE_TELNETD == 1)
	/* telnetd enabled */
	{ NVRAM_SERVICE_OPTION(RC, TELNETD_ENABLE), "1" },
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, TELNETD_BINDING), "lan" },
#elif (HAVE_EZBOX_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, TELNETD_BINDING), "wan" },
#endif
#endif

#if (HAVE_EZBOX_SERVICE_DNSMASQ == 1)
	/* dnsmasq enabled */
	{ NVRAM_SERVICE_OPTION(RC, DNSMASQ_ENABLE), "1" },
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, DNSMASQ_BINDING), "lan" },
#elif (HAVE_EZBOX_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, DNSMASQ_BINDING), "wan" },
#endif
	{ NVRAM_SERVICE_OPTION(DNSMASQ, USER), "root" },
	{ NVRAM_SERVICE_OPTION(DNSMASQ, BOGUS_PRIV), "1" },
	{ NVRAM_SERVICE_OPTION(DNSMASQ, BIND_INTERFACES), "1" },
	{ NVRAM_SERVICE_OPTION(DNSMASQ, MIN_PORT), "10001" },
	/* dnsmasq DHCP server */
	/* Enable DHCP server [1|0] */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_ENABLE), "1" },
	/* First assignable DHCP address */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_START_IPADDR), 
	  EZCFG_DNSMASQ_DEFAULT_DHCPD_START_IPADDR },
	/* Last assignable DHCP address */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_END_IPADDR),
	  EZCFG_DNSMASQ_DEFAULT_DHCPD_END_IPADDR },
	/* DHCP IP address netmask */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_NETMASK),
	  EZCFG_LAN_DEFAULT_NETMASK },
	/* LAN lease time in minutes */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_LEASE),
	  EZCFG_DNSMASQ_DEFAULT_DHCPD_LEASE },
	/* LAN DHCP gateway IP address */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_GATEWAY), "" },
	/* LAN DHCP DNS server use WAN settings */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_WAN_DNS_ENABLE), "1" },
	/* LAN DHCP DNS server IP address */
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_DNS1), "" },
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_DNS2), "" },
	{ NVRAM_SERVICE_OPTION(DNSMASQ, DHCPD_DNS3), "" },
#endif

#if (HAVE_EZBOX_SERVICE_IPTABLES == 1)
	/* iptables enabled */
	{ NVRAM_SERVICE_OPTION(RC, IPTABLES_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(RC, IPTABLES_BINDING), "wan" },
#if (HAVE_EZBOX_SERVICE_IPTABLES_FIREWALL == 1)
	/* firewall support */
	{ NVRAM_SERVICE_OPTION(IPTABLES, FIREWALL_ENABLE), "1" },
#endif
#if (HAVE_EZBOX_SERVICE_IPTABLES_NAT == 1)
	/* NAT support */
	{ NVRAM_SERVICE_OPTION(IPTABLES, NAT_ENABLE), "1" },
#endif
#if (HAVE_EZBOX_SERVICE_IPTABLES_DMZ == 1)
	/* DMZ support */
	{ NVRAM_SERVICE_OPTION(IPTABLES, DMZ_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(IPTABLES, DMZ_DST_IPADDR), "" },
#endif
#endif

#if (HAVE_EZBOX_SERVICE_DHISD == 1)
	/* dhisd enabled */
	{ NVRAM_SERVICE_OPTION(RC, DHISD_ENABLE), "1" },
	/* DHIS server */
	/* server config */
	{ NVRAM_SERVICE_OPTION(DHISD, LOG_FILE), "/var/log/dhis/dhisd.log" },
	{ NVRAM_SERVICE_OPTION(DHISD, PID_FILE), "/var/run/dhis/dhisd.pid" },
	{ NVRAM_SERVICE_OPTION(DHISD, BIND_ADDRESS), "0.0.0.0" },
	{ NVRAM_SERVICE_OPTION(DHISD, BIND_PORT), "58800" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_FILE), "/etc/dhisd.db" },
	{ NVRAM_SERVICE_OPTION(DHISD, MYSQL_SERVER), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, MYSQL_USER), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, MYSQL_PASSWORD), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, MYSQL_DBASE), "" },
	/* server entry number */
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_NUM), "0" },
	/* server db entry 1 settings */
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_HOST_ID), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_HOST_NAME), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_QRC_ENABLE), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_HOST_PASS), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_AUTH_N0), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_AUTH_N1), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_AUTH_N2), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_AUTH_N3), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_ON_CMD), "" },
	{ NVRAM_SERVICE_OPTION(DHISD, DB_ENTRY_0_OFF_CMD), "" },
#endif

#if (HAVE_EZBOX_SERVICE_DHID == 1)
	/* dhid enabled */
	{ NVRAM_SERVICE_OPTION(RC, DHID_ENABLE), "1" },
	/* DHIS client */
	/* client entry number */
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_NUM), "0" },
	/* client entry 1 settings */
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_HOST_ID), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_QRC_ENABLE), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_HOST_PASS), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_AUTH_P0), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_AUTH_P1), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_AUTH_Q0), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_AUTH_Q1), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_IS_ADDR0), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_IS_ADDR1), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_REFRESH), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_ON_CMD), "" },
	{ NVRAM_SERVICE_OPTION(DHID, ENTRY_0_OFF_CMD), "" },
#endif

#if (HAVE_EZBOX_SERVICE_DMCRYPT_DATA_PARTITION == 1)
	/* LUKS/dm-crypt data partition key */
	{ NVRAM_SERVICE_OPTION(DMCRYPT, DATA_PARTITION_KEY), "" },
#endif

#if (HAVE_EZBOX_SERVICE_NANO_X == 1)
	/* nano-X enabled */
	{ NVRAM_SERVICE_OPTION(RC, NANO_X_ENABLE), "1" },
	/* nano-X mouse port */
	{ NVRAM_SERVICE_OPTION(NANO_X, MOUSE_PORT), "/dev/input/mouse0" },
	/* nano-X console device */
	{ NVRAM_SERVICE_OPTION(NANO_X, CONSOLE), "/dev/console" },
#elif (HAVE_EZBOX_SERVICE_KDRIVE == 1)
	/* TinyX/kdrive enabled */
	{ NVRAM_SERVICE_OPTION(RC, KDRIVE_ENABLE), "1" },
	/* TinyX/kdrive mouse driver */
	{ NVRAM_SERVICE_OPTION(KDRIVE, MOUSE_DRIVER), "mouse" },
	/* TinyX/kdrive mouse device */
	{ NVRAM_SERVICE_OPTION(KDRIVE, MOUSE_DEVICE), "/dev/input/mouse0" },
	/* TinyX/kdrive mouse protocol */
	{ NVRAM_SERVICE_OPTION(KDRIVE, MOUSE_PROTOCOL), "ps/2" },
	/* TinyX/kdrive keybd driver */
	{ NVRAM_SERVICE_OPTION(KDRIVE, KEYBD_DRIVER), "keyboard" },
#endif

#if (HAVE_EZBOX_SERVICE_DILLO == 1)
	/* dillo enabled */
	{ NVRAM_SERVICE_OPTION(RC, DILLO_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, GEOMETRY), "780x580" },
	{ NVRAM_SERVICE_OPTION(DILLO, LOAD_IMAGES), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, LOAD_STYLESHEETS), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, PARSE_EMBEDDED_CSS), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, FILTER_AUTO_REQUESTS), "same_domain" },
	{ NVRAM_SERVICE_OPTION(DILLO, BUFFERED_DRAWING), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SAVE_DIR), "/tmp" },
#if 0
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_SERIF), "DejaVu Serif" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_SANS_SERIF), "DejaVu Sans" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_CURSIVE), "URW Chancery L" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_FANTASY), "DejaVu Sans" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_MONOSPACE), "DejaVu Sans Mono" },
#else
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_SERIF), "WenQuanYi Zen Hei" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_SANS_SERIF), "WenQuanYi Zen Hei Sharp" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_CURSIVE), "WenQuanYi Zen Hei" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_FANTASY), "WenQuanYi Zen Hei Sharp" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_MONOSPACE), "WenQuanYi Zen Hei Mono" },
#endif
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_FACTOR), "1.0" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_MAX_SIZE), "100" },
	{ NVRAM_SERVICE_OPTION(DILLO, FONT_MIN_SIZE), "12" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_TOOLTIP), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, W3C_PLUS_HEURISTICS), "0" },
	{ NVRAM_SERVICE_OPTION(DILLO, START_PAGE),
		"http://" EZCFG_LOOPBACK_DEFAULT_IPADDR "/" },
	{ NVRAM_SERVICE_OPTION(DILLO, HOME),
		"http://" EZCFG_LOOPBACK_DEFAULT_IPADDR "/" },
#if 0
	{ NVRAM_SERVICE_OPTION(DILLO, SEARCH_URL),
		"http://www.google.com/search?ie=UTF-8&oe=UTF-8&q=%s" },
	{ NVRAM_SERVICE_OPTION(DILLO, HTTP_LANGUAGE), "en-US" },
	{ NVRAM_SERVICE_OPTION(DILLO, HTTP_MAX_CONNS), "6" },
	{ NVRAM_SERVICE_OPTION(DILLO, HTTP_PROXY), "http://localhost:8080/" },
	{ NVRAM_SERVICE_OPTION(DILLO, HTTP_PROXYUSER), "joe" },
	{ NVRAM_SERVICE_OPTION(DILLO, NO_PROXY), "localhost 127.0.0.1" },
#endif
	{ NVRAM_SERVICE_OPTION(DILLO, HTTP_REFERER), "host" },
#if 0
	{ NVRAM_SERVICE_OPTION(DILLO, HTTP_USER_AGENT), "Dillo/2.2" },
#endif
	{ NVRAM_SERVICE_OPTION(DILLO, BG_COLOR), "0xdcd1ba" },
	{ NVRAM_SERVICE_OPTION(DILLO, ALLOW_WHITE_BG), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, CONTRAST_VISITED_COLOR), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, PANEL_SIZE), "small" },
	{ NVRAM_SERVICE_OPTION(DILLO, SMALL_ICONS), "0" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_BACK), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_FORW), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_HOME), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_RELOAD), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_SAVE), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_STOP), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_BOOKMARKS), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_TOOLS), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_FILEMENU), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_CLEAR_URL), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_URL), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_SEARCH), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_HELP), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_PROGRESS_BOX), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, FULLWINDOW_START), "0" },
	{ NVRAM_SERVICE_OPTION(DILLO, ENTERPRESS_FORCES_SUBMIT), "0" },
	{ NVRAM_SERVICE_OPTION(DILLO, MIDDLE_CLICK_OPENS_NEW_TAB), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, MIDDLE_CLICK_DRAGS_PAGE), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, FOCUS_NEW_TAB), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_MSG), "1" },
	{ NVRAM_SERVICE_OPTION(DILLO, SHOW_EXTRA_WARNINGS), "1" },
#endif

#if (HAVE_EZBOX_SERVICE_EMC2 == 1)
	/* EMC2 enabled */
	{ NVRAM_SERVICE_OPTION(RC, EMC2_ENABLE), "0" },
	{ NVRAM_SERVICE_OPTION(EMC2, MODULES),
		"rtai_hal,rtai_sched,rtai_fifos,rtai_sem,rtai_math,emc2/rtapi,emc2/hal_lib" },
	{ NVRAM_SERVICE_OPTION(EMC2, MODPATH), "/usr/realtime/modules" },
	{ NVRAM_SERVICE_OPTION(EMC2, RTLIB_DIR), "/usr/realtime/modules/emc2" },
	{ NVRAM_SERVICE_OPTION(EMC2, RTAPI_DEBUG), "5" },
	{ NVRAM_SERVICE_OPTION(EMC2, INIFILE), "/root/emc2/configs/ezcnc.ini" },
	{ NVRAM_SERVICE_OPTION(EMC2, RESTORE_DEFAULTS), "0" },
	/* EMC2 Latency test */
	{ NVRAM_SERVICE_OPTION(EMC2, LAT_TEST_ENABLE), "1" },
	{ NVRAM_SERVICE_OPTION(EMC2, LAT_BASE_PERIOD), "25000" },
	{ NVRAM_SERVICE_OPTION(EMC2, LAT_SERVO_PERIOD), "1000000" },

	/* [EMC] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMC_VERSION), "1.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMC_MACHINE), "EZCNC" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMC_DEBUG), "1" },
	/* [DISPLAY] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_DISPLAY), "xemc" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_CYCLE_TIME), "0.200" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_HELP_FILE), "xemc.txt" },
	/* RELATIVE or MACHINE */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_POSITION_OFFSET), "RELATIVE" },
	/* COMMANDED or ACTUAL */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_POSITION_FEEDBACK), "ACTUAL" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_MAX_FEED_OVERRIDE), "1.2" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_PROGRAM_PREFIX), "/var/emc2/nc_files" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_INTRO_GRAPHIC), "emc2.gif" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_DISPLAY_INTRO_TIME), "5" },
	/* [TASK] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TASK_TASK), "milltask" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TASK_CYCLE_TIME), "0.010" },
	/* [RS274NGC] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_RS274NGC_PARAMETER_FILE), "ezcnc_rs274ngc.var" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_RS274NGC_LOG_FILE), "ezcnc_rs274ngc.log" },
	/* [EMCMOT] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCMOT_EMCMOT), "motmod" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCMOT_COMM_TIMEOUT), "1.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCMOT_COMM_WAIT), "0.010" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCMOT_BASE_PERIOD), "50000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCMOT_SERVO_PERIOD), "1000000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCMOT_TRAJ_PERIOD), "100000" },
	/* [HAL] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_HAL_HALFILE_NUM), "0" },
	/* hal command number */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_HAL_HALCMD_NUM), "0" },
	/* [TRAJ] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_AXES), "3" },
	/* COORDINATES = X Y Z A B C */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_COORDINATES), "X Y Z" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_HOME), "0 0 0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_LINEAR_UNITS), "mm" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_ANGULAR_UNITS), "degree" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_CYCLE_TIME), "0.010" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_DEFAULT_VELOCITY), "2.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_MAX_VELOCITY), "20.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_DEFAULT_ACCELERATION), "4.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_TRAJ_MAX_ACCELERATION), "40.0" },
	/* [EMCIO] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCIO_EMCIO), "io" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCIO_CYCLE_TIME), "0.100" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_EMCIO_TOOL_TABLE), "ezcnc.tbl" },
	/* [AXIS_0] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_TYPE), "LINEAR" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_HOME), "0.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_MAX_VELOCITY), "8.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_MAX_ACCELERATION), "16.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_STEPGEN_MAXACCEL), "32.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_BACKLASH), "0.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_SCALE), "533.333333" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_OUTPUT_SCALE), "1.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_MIN_LIMIT), "-1000.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_MAX_LIMIT), "1000.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_FERROR), "1.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_MIN_FERROR), "0.05" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_HOME_OFFSET), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_HOME_SEARCH_VEL), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_HOME_LATCH_VEL), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_HOME_USE_INDEX), "NO" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_0_HOME_IGNORE_LIMITS), "NO" },
	/* [AXIS_1] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_TYPE), "LINEAR" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_HOME), "0.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_MAX_VELOCITY), "8.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_MAX_ACCELERATION), "16.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_STEPGEN_MAXACCEL), "32.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_BACKLASH), "0.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_SCALE), "533.333333" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_OUTPUT_SCALE), "1.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_MIN_LIMIT), "-1000.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_MAX_LIMIT), "1000.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_FERROR), "1.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_MIN_FERROR), "0.05" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_HOME_OFFSET), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_HOME_SEARCH_VEL), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_HOME_LATCH_VEL), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_HOME_USE_INDEX), "NO" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_1_HOME_IGNORE_LIMITS), "NO" },
	/* [AXIS_2] section */
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_TYPE), "LINEAR" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_HOME), "0.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_MAX_VELOCITY), "8.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_MAX_ACCELERATION), "16.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_STEPGEN_MAXACCEL), "32.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_BACKLASH), "0.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_SCALE), "533.333333" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_OUTPUT_SCALE), "1.000" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_MIN_LIMIT), "-1000.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_MAX_LIMIT), "1000.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_FERROR), "1.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_MIN_FERROR), "0.05" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_HOME_OFFSET), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_HOME_SEARCH_VEL), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_HOME_LATCH_VEL), "0.0" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_HOME_USE_INDEX), "NO" },
	{ NVRAM_SERVICE_OPTION(EMC2, CONF_AXIS_2_HOME_IGNORE_LIMITS), "NO" },

#endif

#if (HAVE_EZBOX_SERVICE_COOVA_CHILLI == 1)
	/* coova-chilli enabled */
	{ NVRAM_SERVICE_OPTION(RC, COOVA_CHILLI_ENABLE), "0" },
#endif

#if (HAVE_EZBOX_SERVICE_LXC == 1)
	/* LXC enabled */
	{ NVRAM_SERVICE_OPTION(RC, LXC_ENABLE), "0" },
	/* number of containers */
	{ NVRAM_SERVICE_OPTION(LXC, CONTAINER_NUMBER), "1" },
	/* settings for container 1 */
	/* specify the architecture for the container. x86, i686, x86_64, amd64 */
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_ARCH), "x86_64" },
	/* specify the hostname for the container */
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_UTSNAME), "lxc1" },
	/* specify what kind of network virtualization to be used for the container. */
	/* [empty|veth|vlan|macvlan|phys] */
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_TYPE), "veth" },
	/* specify an action to do for the network. */
	/* up: activates the interface. */
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_FLAGS), "up" },
	/* specify the interface to be used for real network traffic. */
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_LINK), "br-lxc" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_NAME), "eth0" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_HWADDR), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_IPV4), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_IPV6), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_NETWORK_SCRIPT_UP), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_PTS), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_CONSOLE), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_TTY), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_DEVTTYDIR), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_MOUNT), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_MOUNT_ENTRY), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_ROOTFS), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_ROOTFS_MOUNT), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_PIVOTDIR), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_CGROUP_CPUSET_CPUS), "" },
	{ NVRAM_SERVICE_OPTION(LXC, CONF_1_LXC_CAP_DROP), "" },
#endif

#if (HAVE_EZBOX_SERVICE_RADVD == 1)
	/* RADVD enabled */
	{ NVRAM_SERVICE_OPTION(RC, RADVD_ENABLE), "0" },
	/* number of interfaces */
	{ NVRAM_SERVICE_OPTION(RADVD, INTERFACE_NUMBER), "1" },
	/* settings for interface 1 */
	/* specify the interface name */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_NAME), "eth0" },
	/* specify the interface IgnoreIfMissing option [on|off] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_IGNORE_IF_MISSING), "" },
	/* specify the interface AdvSendAdvert option [on|off] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_SEND_ADVERT), "on" },
	/* specify the interface UnicastOnly option [on|off] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_UNICAST_ONLY), "" },
	/* specify the interface MaxRtrAdvInterval option [4 - 1800] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_MAX_RTR_ADV_INTERVAL), "60" },
	/* specify the interface MinRtrAdvInterval option [3 - 0.75 * MaxRtrAdvInterval] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_MIN_RTR_ADV_INTERVAL), "20" },
	/* specify the interface MinDelayBetweenRAs option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_MIN_DELAY_BETWEEN_RAS), "" },
	/* specify the interface AdvManagedFlag option [on|off] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_MANAGED_FLAG), "" },
	/* specify the interface AdvOtherConfigFlag option [on|off] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_OTHER_CONFIG_FLAG), "on" },
	/* specify the interface AdvLinkMTU option [1280 - link maximum MTU] */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_LINK_MTU), "1492" },
	/* specify the interface AdvReachableTime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_REACHABLE_TIME), "" },
	/* specify the interface AdvRetransTimer option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_RETRANS_TIMER), "" },
	/* specify the interface AdvCurHopLimit option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_CUR_HOP_LIMIT), "" },
	/* specify the interface AdvDefaultLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_DEFAULT_LIFETIME), "" },
	/* specify the interface AdvDefaultPreference option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_DEFAULT_PREFERENCE), "" },
	/* specify the interface AdvSourceLLAddress option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_SOURCE_LL_ADDRESS), "" },
	/* specify the interface AdvHomeAgentFlag option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_HOME_AGENT_FLAG), "" },
	/* specify the interface AdvHomeAgentInfo option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_HOME_AGENT_INFO), "" },
	/* specify the interface HomeAgentLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_HOME_AGENT_LIFETIME), "" },
	/* specify the interface HomeAgentPreference option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_HOME_AGENT_PREFERENCE), "" },
	/* specify the interface AdvMobRtrSupportFlag option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_MOB_RTR_SUPPORT_FLAG), "" },
	/* specify the interface AdvIntervalOpt option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ADV_INTERVAL_OPT), "" },
	/* number of prefix for interface 1 */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_NUMBER), "1" },
	/* settings for prefix for interface 1 */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_PREFIX), "" },
	/* specify the prefix AdvOnLink option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_ADV_ON_LINK), "" },
	/* specify the prefix AdvAutonomous option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_ADV_AUTONOMOUS), "" },
	/* specify the prefix AdvRouterAddr option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_ADV_ROUTER_ADDR), "" },
	/* specify the prefix AdvValidLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_ADV_VALID_LIFETIME), "" },
	/* specify the prefix AdvPreferredLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_ADV_PREFERRED_LIFETIME), "" },
	/* specify the prefix DeprecatePrefix option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_DEPRECATE_PREFIX), "" },
	/* specify the prefix DecrementLifetimes option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_DECREMENT_LIFETIMES), "" },
	/* specify the prefix Base6Interface option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_BASE_6_INTERFACE), "" },
	/* specify the prefix Base6to4Interface option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_PREFIX_1_BASE_6TO4_INTERFACE), "" },
	/* number of clients for interface 1 */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_CLIENTS_NUMBER), "1" },
	/* settings for clients for interface 1 */
	/* specify the clients IPv6 Address list */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_CLIENTS_1_IPV6_ADDRESS_1), "" },
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_CLIENTS_1_IPV6_ADDRESS_2), "" },
	/* settings for route for interface 1 */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ROUTE_1_PREFIX), "" },
	/* specify the route AdvRouteLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ROUTE_1_ADV_ROUTE_LIFETIME), "" },
	/* specify the route AdvRoutePreference option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ROUTE_1_ADV_ROUTE_PREFERENCE), "" },
	/* specify the route RemoveRoute option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_ROUTE_1_REMOVE_ROUTE), "" },
	/* settings for RDNSS for interface 1 */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_RDNSS_1_IPS), "fe80::1" },
	/* specify the RDNSS AdvRDNSSLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_RDNSS_1_ADV_RDNSS_LIFETIME), "60" },
	/* specify the RDNSS FlushRDNSS option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_RDNSS_1_FLUSH_RDNSS), "" },
	/* settings for DNSSL for interface 1 */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_DNSSL_1_SUFFIXES), "" },
	/* specify the DNSSL AdvDNSSLLifetime option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_DNSSL_1_ADV_DNSSL_LIFETIME), "" },
	/* specify the DNSSL FlushDNSSL option */
	{ NVRAM_SERVICE_OPTION(RADVD, IF_1_DNSSL_1_FLUSH_DNSSL), "" },
#endif

#if (HAVE_EZBOX_SERVICE_PPP == 1)
	/* ppp pap secrets entry number */
	{ NVRAM_SERVICE_OPTION(PPP, PAP_SECRET_ENTRY_NUM), "0" },
	/* ppp chap secrets entry number */
	{ NVRAM_SERVICE_OPTION(PPP, CHAP_SECRET_ENTRY_NUM), "0" },
#endif

#if (HAVE_EZBOX_SERVICE_PPPOE_SERVER == 1)
	/* pppoe-server enabled */
	{ NVRAM_SERVICE_OPTION(RC, PPPOE_SERVER_ENABLE), "0" },
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, PPPOE_SERVER_BINDING), "lan" },
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, IFNAME), "br-lan" },
#elif (HAVE_EZBOX_ETH_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, IFNAME), "eth0" },
#elif (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, IFNAME), "wlan0" },
#else
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, IFNAME), "" },
#endif
#elif (HAVE_EZBOX_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, PPPOE_SERVER_BINDING), "wan" },
#if (HAVE_EZBOX_ETH_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, IFNAME), "eth1" },
#else
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, IFNAME), "" },
#endif
#endif
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, LOCAL_IPADDR),
		EZCFG_PPPOE_SERVER_DEFAULT_LOCAL_IPADDR },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, REMOTE_IPADDR),
		EZCFG_PPPOE_SERVER_DEFAULT_REMOTE_IPADDR },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, SESSION_NUMBER), "50" },
	/* PPP general options */
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_DEBUG), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_KDEBUG), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IDLE), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_MAXCONNECT), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_DOMAIN), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_PERSIST), "1" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_DEMAND), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LOGFILE), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LINKNAME), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IFNAME), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_MAXFAIL), "10" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_KTUNE), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_CONNECT_DELAY), "1000" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_UNIT), "-1" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_DUMP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_DRYRUN), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_CHILD_TIMEOUT), "5" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IP_UP_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IP_DOWN_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPV6_UP_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPV6_DOWN_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_PLUGIN), "" },
	/* PPP auth options */
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_AUTH), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REQUIRE_PAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REQUIRE_CHAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REQUIRE_MSCHAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REQUIRE_MSCHAP_V2), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REFUSE_PAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REFUSE_CHAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REFUSE_MSCHAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REFUSE_MSCHAP_V2), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REQUIRE_EAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REFUSE_EAP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NAME), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_USER), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_PASSWORD), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_USEHOSTNAME), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REMOTENAME), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LOGIN), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_ENABLE_SESSION), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_PAPCRYPT), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_PRIVGROUP), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_ALLOW_IP), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REMOTENUMBER), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_ALLOW_NUMBER), "" },
	/* PPP LCP options */
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_MRU), "1492" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_MTU), "1492" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LCP_ECHO_FAILURE), "3" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LCP_ECHO_INTERVAL), "60" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LCP_RESTART), "3" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LCP_MAX_TERMINATE), "2" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LCP_MAX_CONFIGURE), "10" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LCP_MAX_FAILURE), "5" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_RECEIVE_ALL), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOENDPOINT), "0" },
	/* PPP IPCP options */
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOIP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOVJ), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOVJCCOMP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_VJ_MAX_SLOTS), "16" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_ACCEPT_LOCAL), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_ACCEPT_REMOTE), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPPARAM), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOIPDEFAULT), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_MS_DNS), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_MS_WINS), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_RESTART), "3" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_MAX_TERMINATE), "2" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_MAX_CONFIGURE), "10" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_MAX_FAILURE), "5" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_DEFAULTROUTE), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_REPLACEDEFAULTROUTE), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_PROXYARP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_USEPEERDNS), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NETMASK), "" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_NO_ADDRESSES), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IPCP_NO_ADDRESS), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOREMOTEIP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_NOSENDIP), "0" },
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_IP_ADDRESSES), "" },
	/* PPP tty options */
	{ NVRAM_SERVICE_OPTION(PPPOE_SERVER, PPP_LOCK), "1" },
#endif

#if (HAVE_EZBOX_SERVICE_PPP_RP_PPPOE == 1)
	/* rp-pppoe client enabled */
	{ NVRAM_SERVICE_OPTION(RC, PPP_RP_PPPOE_ENABLE), "0" },
	/* PPP general options */
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_DEBUG), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_KDEBUG), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IDLE), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_MAXCONNECT), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_DOMAIN), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_PERSIST), "1" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_DEMAND), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LOGFILE), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LINKNAME), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IFNAME), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_MAXFAIL), "10" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_KTUNE), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_CONNECT_DELAY), "1000" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_UNIT), "-1" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_DUMP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_DRYRUN), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_CHILD_TIMEOUT), "5" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IP_UP_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IP_DOWN_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPV6_UP_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPV6_DOWN_SCRIPT), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_PLUGIN), "rp-pppoe.so" },
	/* PPP auth options */
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_AUTH), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REQUIRE_PAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REQUIRE_CHAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REQUIRE_MSCHAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REQUIRE_MSCHAP_V2), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REFUSE_PAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REFUSE_CHAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REFUSE_MSCHAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REFUSE_MSCHAP_V2), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REQUIRE_EAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REFUSE_EAP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NAME), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_USER), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_PASSWORD), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_USEHOSTNAME), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REMOTENAME), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LOGIN), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_ENABLE_SESSION), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_PAPCRYPT), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_PRIVGROUP), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_ALLOW_IP), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REMOTENUMBER), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_ALLOW_NUMBER), "" },
	/* PPP LCP options */
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_MRU), "1492" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_MTU), "1492" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LCP_ECHO_FAILURE), "3" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LCP_ECHO_INTERVAL), "60" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LCP_RESTART), "3" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LCP_MAX_TERMINATE), "2" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LCP_MAX_CONFIGURE), "10" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LCP_MAX_FAILURE), "5" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_RECEIVE_ALL), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOENDPOINT), "0" },
	/* PPP IPCP options */
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOIP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOVJ), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOVJCCOMP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_VJ_MAX_SLOTS), "16" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_ACCEPT_LOCAL), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_ACCEPT_REMOTE), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPPARAM), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOIPDEFAULT), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_MS_DNS), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_MS_WINS), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_RESTART), "3" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_MAX_TERMINATE), "2" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_MAX_CONFIGURE), "10" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_MAX_FAILURE), "5" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_DEFAULTROUTE), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_REPLACEDEFAULTROUTE), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_PROXYARP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_USEPEERDNS), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NETMASK), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_NO_ADDRESSES), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IPCP_NO_ADDRESS), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOREMOTEIP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_NOSENDIP), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_IP_ADDRESSES), "" },
	/* PPP tty options */
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPP_LOCK), "1" },
	/* PPP rp-pppoe plugin options */
#if (HAVE_EZBOX_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, PPP_RP_PPPOE_BINDING), "wan" },
#if (HAVE_EZBOX_ETH_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, DEVICE_NAME), "nic-eth1" },
#else
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, DEVICE_NAME), "" },
#endif
#elif (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, PPP_RP_PPPOE_BINDING), "lan" },
#if (HAVE_EZBOX_BR_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, DEVICE_NAME), "nic-br-lan" },
#elif (HAVE_EZBOX_ETH_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, DEVICE_NAME), "nic-eth0" },
#elif (HAVE_EZBOX_WIFI_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, DEVICE_NAME), "nic-wlan0" },
#else
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, DEVICE_NAME), "" },
#endif
#endif
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, RP_PPPOE_SERVICE), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, RP_PPPOE_AC), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, RP_PPPOE_SESS), "" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, RP_PPPOE_VERBOSE), "0" },
	{ NVRAM_SERVICE_OPTION(RP_PPPOE, PPPOE_MAC), "" },
#endif

#if (HAVE_EZBOX_SERVICE_FREERADIUS2_SERVER == 1)
	/* freeradius2 server enabled */
	{ NVRAM_SERVICE_OPTION(RC, FREERADIUS2_SERVER_ENABLE), "0" },
#if (HAVE_EZBOX_LAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, FREERADIUS2_SERVER_BINDING), "lan" },
#elif (HAVE_EZBOX_WAN_NIC == 1)
	{ NVRAM_SERVICE_OPTION(RC, FREERADIUS2_SERVER_BINDING), "wan" },
#endif
	{ NVRAM_SERVICE_OPTION(FREERADIUS2_SERVER, NAME), "radiusd" },
	{ NVRAM_SERVICE_OPTION(FREERADIUS2_SERVER, IPADDR),
		EZCFG_FREERADIUS2_SERVER_DEFAULT_IPADDR },
	{ NVRAM_SERVICE_OPTION(FREERADIUS2_SERVER, PORT),
		EZCFG_FREERADIUS2_SERVER_DEFAULT_PORT },
#endif

};

char *default_nvram_savings[] = {
	NVRAM_SERVICE_OPTION(SYS, SERIAL_NUMBER),
	NVRAM_SERVICE_OPTION(EZCFG, SYS_LANGUAGE),
};

/* Public functions */
int ezcfg_nvram_get_num_default_nvram_settings(void)
{
	return ARRAY_SIZE(default_nvram_settings);
}

int ezcfg_nvram_get_num_default_nvram_savings(void)
{
	return ARRAY_SIZE(default_nvram_savings);
}
