/* ============================================================================
 * Project Name : ezbox configuration utilities
 * File Name    : ezcfg-radvd.h
 *
 * Description  : interface to configurate ezbox information
 *
 * Copyright (C) 2008-2014 by ezbox-project
 *
 * History      Rev       Description
 * 2012-08-21   0.1       Write it from scratch
 * ============================================================================
 */

#ifndef _EZCFG_RADVD_H_
#define _EZCFG_RADVD_H_

/* ezcfg nvram name prefix */
#define EZCFG_RADVD_NVRAM_PREFIX              "radvd."

#define EZCFG_RADVD_INTERFACE_NUMBER          "interface_number"
#define EZCFG_RADVD_PREFIX_NUMBER             "prefix_number"
#define EZCFG_RADVD_CLIENTS_NUMBER            "clients_number"
#define EZCFG_RADVD_ROUTE_NUMBER              "route_number"
#define EZCFG_RADVD_RDNSS_NUMBER              "RDNSS_number"
#define EZCFG_RADVD_DNSSL_NUMBER              "DNSSL_number"
#define EZCFG_RADVD_IF                        "if"
#define EZCFG_RADVD_P                         "p"
#define EZCFG_RADVD_C                         "c"
#define EZCFG_RADVD_R                         "r"
#define EZCFG_RADVD_S                         "s"
#define EZCFG_RADVD_L                         "l"
#define EZCFG_RADVD_NAME                      "name"
#define EZCFG_RADVD_IPS                       "ips"
#define EZCFG_RADVD_SUFFIXES                  "suffixes"

#define EZCFG_RADVD_IPV6_ADDRESS              "ipv6_address"
#define EZCFG_RADVD_IPV6_ADDRESS_NUMBER       "ipv6_address_number"

/* keywords */
#define EZCFG_RADVD_CONF_KEYWORD_INTERFACE    "interface"
#define EZCFG_RADVD_CONF_KEYWORD_PREFIX       "prefix"
#define EZCFG_RADVD_CONF_KEYWORD_CLIENTS      "clients"
#define EZCFG_RADVD_CONF_KEYWORD_ROUTE        "route"
#define EZCFG_RADVD_CONF_KEYWORD_RDNSS        "RDNSS"
#define EZCFG_RADVD_CONF_KEYWORD_DNSSL        "DNSSL"

/* INTERFACE SPECIFIC OPTIONS */
#define EZCFG_RADVD_CONF_KEYWORD_IGNORE_IF_MISSING \
	"IgnoreIfMissing"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_SEND_ADVERT \
	"AdvSendAdvert"
#define EZCFG_RADVD_CONF_KEYWORD_UNICAST_ONLY \
	"UnicastOnly"
#define EZCFG_RADVD_CONF_KEYWORD_MAX_RTR_ADV_INTERVAL \
	"MaxRtrAdvInterval"
#define EZCFG_RADVD_CONF_KEYWORD_MIN_RTR_ADV_INTERVAL \
	"MinRtrAdvInterval"
#define EZCFG_RADVD_CONF_KEYWORD_MIN_DELAY_BETWEEN_RAS \
	"MinDelayBetweenRAs"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_MANAGED_FLAG \
	"AdvManagedFlag"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_OTHER_CONFIG_FLAG \
	"AdvOtherConfigFlag"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_LINK_MTU \
	"AdvLinkMTU"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_REACHABLE_TIME \
	"AdvReachableTime"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_RETRANS_TIMER \
	"AdvRetransTimer"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_CUR_HOP_LIMIT \
	"AdvCurHopLimit"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_DEFAULT_LIFETIME \
	"AdvDefaultLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_DEFAULT_PREFERENCE \
	"AdvDefaultPreference"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_SOURCE_LL_ADDRESS \
	"AdvSourceLLAddress"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_HOME_AGENT_FLAG \
	"AdvHomeAgentFlag"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_HOME_AGENT_INFO \
	"AdvHomeAgentInfo"
#define EZCFG_RADVD_CONF_KEYWORD_HOME_AGENT_LIFETIME \
	"HomeAgentLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_HOME_AGENT_PREFERENCE \
	"HomeAgentPreference"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_MOB_RTR_SUPPORT_FLAG \
	"AdvMobRtrSupportFlag"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_INTERVAL_OPT \
	"AdvIntervalOpt"

/* PREFIX SPECIFIC OPTIONS */
#define EZCFG_RADVD_CONF_KEYWORD_ADV_ON_LINK \
	"AdvOnLink"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_AUTONOMOUS \
	"AdvAutonomous"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_ROUTER_ADDR \
	"AdvRouterAddr"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_VALID_LIFETIME \
	"AdvValidLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_PREFERRED_LIFETIME \
	"AdvPreferredLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_DEPRECATE_PREFIX \
	"DeprecatePrefix"
#define EZCFG_RADVD_CONF_KEYWORD_DECREMENT_LIFETIMES \
	"DecrementLifetimes"
#define EZCFG_RADVD_CONF_KEYWORD_BASE_6_INTERFACE \
	"Base6Interface"
#define EZCFG_RADVD_CONF_KEYWORD_BASE_6TO4_INTERFACE \
	"Base6to4Interface"

/* ROUTE SPECIFIC OPTIONS */
#define EZCFG_RADVD_CONF_KEYWORD_ADV_ROUTE_LIFETIME \
	"AdvRouteLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_ADV_ROUTE_PREFERENCE \
	"AdvRoutePreference"
#define EZCFG_RADVD_CONF_KEYWORD_REMOVE_ROUTE \
	"RemoveRoute"

/* RDNSS SPECIFIC OPTIONS */
#define EZCFG_RADVD_CONF_KEYWORD_ADV_RDNSS_LIFETIME \
	"AdvRDNSSLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_FLUSH_RDNSS \
	"FlushRDNSS"

/* DNSSL SPECIFIC OPTIONS */
#define EZCFG_RADVD_CONF_KEYWORD_ADV_DNSSL_LIFETIME \
	"AdvDNSSLLifetime"
#define EZCFG_RADVD_CONF_KEYWORD_FLUSH_DNSSL \
	"FlushDNSSL"

/* interface 1 settings */
#define EZCFG_RADVD_IF_1_NAME \
	"if1." EZCFG_RADVD_NAME
#define EZCFG_RADVD_IF_1_IGNORE_IF_MISSING \
	"if1." EZCFG_RADVD_CONF_KEYWORD_IGNORE_IF_MISSING
#define EZCFG_RADVD_IF_1_ADV_SEND_ADVERT \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_SEND_ADVERT
#define EZCFG_RADVD_IF_1_UNICAST_ONLY \
	"if1." EZCFG_RADVD_CONF_KEYWORD_UNICAST_ONLY
#define EZCFG_RADVD_IF_1_MAX_RTR_ADV_INTERVAL \
	"if1." EZCFG_RADVD_CONF_KEYWORD_MAX_RTR_ADV_INTERVAL
#define EZCFG_RADVD_IF_1_MIN_RTR_ADV_INTERVAL \
	"if1." EZCFG_RADVD_CONF_KEYWORD_MIN_RTR_ADV_INTERVAL
#define EZCFG_RADVD_IF_1_MIN_DELAY_BETWEEN_RAS \
	"if1." EZCFG_RADVD_CONF_KEYWORD_MIN_DELAY_BETWEEN_RAS
#define EZCFG_RADVD_IF_1_ADV_MANAGED_FLAG \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_MANAGED_FLAG
#define EZCFG_RADVD_IF_1_ADV_OTHER_CONFIG_FLAG \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_OTHER_CONFIG_FLAG
#define EZCFG_RADVD_IF_1_ADV_LINK_MTU \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_LINK_MTU
#define EZCFG_RADVD_IF_1_ADV_REACHABLE_TIME \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_REACHABLE_TIME
#define EZCFG_RADVD_IF_1_ADV_RETRANS_TIMER \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_RETRANS_TIMER
#define EZCFG_RADVD_IF_1_ADV_CUR_HOP_LIMIT \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_CUR_HOP_LIMIT
#define EZCFG_RADVD_IF_1_ADV_DEFAULT_LIFETIME \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_DEFAULT_LIFETIME
#define EZCFG_RADVD_IF_1_ADV_DEFAULT_PREFERENCE \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_DEFAULT_PREFERENCE
#define EZCFG_RADVD_IF_1_ADV_SOURCE_LL_ADDRESS \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_SOURCE_LL_ADDRESS
#define EZCFG_RADVD_IF_1_ADV_HOME_AGENT_FLAG \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_HOME_AGENT_FLAG
#define EZCFG_RADVD_IF_1_ADV_HOME_AGENT_INFO \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_HOME_AGENT_INFO
#define EZCFG_RADVD_IF_1_HOME_AGENT_LIFETIME \
	"if1." EZCFG_RADVD_CONF_KEYWORD_HOME_AGENT_LIFETIME
#define EZCFG_RADVD_IF_1_HOME_AGENT_PREFERENCE \
	"if1." EZCFG_RADVD_CONF_KEYWORD_HOME_AGENT_PREFERENCE
#define EZCFG_RADVD_IF_1_ADV_MOB_RTR_SUPPORT_FLAG \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_MOB_RTR_SUPPORT_FLAG
#define EZCFG_RADVD_IF_1_ADV_INTERVAL_OPT \
	"if1." EZCFG_RADVD_CONF_KEYWORD_ADV_INTERVAL_OPT

#define EZCFG_RADVD_IF_1_PREFIX_NUMBER \
	"if1." EZCFG_RADVD_PREFIX_NUMBER
#define EZCFG_RADVD_IF_1_CLIENTS_NUMBER \
	"if1." EZCFG_RADVD_CLIENTS_NUMBER
#define EZCFG_RADVD_IF_1_ROUTE_NUMBER \
	"if1." EZCFG_RADVD_ROUTE_NUMBER
#define EZCFG_RADVD_IF_1_RDNSS_NUMBER \
	"if1." EZCFG_RADVD_RDNSS_NUMBER
#define EZCFG_RADVD_IF_1_DNSSL_NUMBER \
	"if1." EZCFG_RADVD_DNSSL_NUMBER

#define EZCFG_RADVD_IF_1_PREFIX_1_PREFIX \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_PREFIX
#define EZCFG_RADVD_IF_1_PREFIX_1_ADV_ON_LINK \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_ADV_ON_LINK
#define EZCFG_RADVD_IF_1_PREFIX_1_ADV_AUTONOMOUS \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_ADV_AUTONOMOUS
#define EZCFG_RADVD_IF_1_PREFIX_1_ADV_ROUTER_ADDR \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_ADV_ROUTER_ADDR
#define EZCFG_RADVD_IF_1_PREFIX_1_ADV_VALID_LIFETIME \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_ADV_VALID_LIFETIME
#define EZCFG_RADVD_IF_1_PREFIX_1_ADV_PREFERRED_LIFETIME \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_ADV_PREFERRED_LIFETIME
#define EZCFG_RADVD_IF_1_PREFIX_1_DEPRECATE_PREFIX \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_DEPRECATE_PREFIX
#define EZCFG_RADVD_IF_1_PREFIX_1_DECREMENT_LIFETIMES \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_DECREMENT_LIFETIMES
#define EZCFG_RADVD_IF_1_PREFIX_1_BASE_6_INTERFACE \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_BASE_6_INTERFACE
#define EZCFG_RADVD_IF_1_PREFIX_1_BASE_6TO4_INTERFACE \
	"if1.p1." EZCFG_RADVD_CONF_KEYWORD_BASE_6TO4_INTERFACE

#define EZCFG_RADVD_IF_1_CLIENTS_1_IPV6_ADDRESS_NUMBER \
	"if1.c1." EZCFG_RADVD_IPV6_ADDRESS_NUMBER
#define EZCFG_RADVD_IF_1_CLIENTS_1_IPV6_ADDRESS_1 \
	"if1.c1." EZCFG_RADVD_IPV6_ADDRESS "1"
#define EZCFG_RADVD_IF_1_CLIENTS_1_IPV6_ADDRESS_2 \
	"if1.c1." EZCFG_RADVD_IPV6_ADDRESS "2"

#define EZCFG_RADVD_IF_1_ROUTE_1_PREFIX \
	"if1.r1." EZCFG_RADVD_CONF_KEYWORD_PREFIX
#define EZCFG_RADVD_IF_1_ROUTE_1_ADV_ROUTE_LIFETIME \
	"if1.r1." EZCFG_RADVD_CONF_KEYWORD_ADV_ROUTE_LIFETIME
#define EZCFG_RADVD_IF_1_ROUTE_1_ADV_ROUTE_PREFERENCE \
	"if1.r1." EZCFG_RADVD_CONF_KEYWORD_ADV_ROUTE_PREFERENCE
#define EZCFG_RADVD_IF_1_ROUTE_1_REMOVE_ROUTE \
	"if1.r1." EZCFG_RADVD_CONF_KEYWORD_REMOVE_ROUTE

#define EZCFG_RADVD_IF_1_RDNSS_1_IPS \
	"if1.s1." EZCFG_RADVD_IPS
#define EZCFG_RADVD_IF_1_RDNSS_1_ADV_RDNSS_LIFETIME \
	"if1.s1." EZCFG_RADVD_CONF_KEYWORD_ADV_RDNSS_LIFETIME
#define EZCFG_RADVD_IF_1_RDNSS_1_FLUSH_RDNSS \
	"if1.s1." EZCFG_RADVD_CONF_KEYWORD_FLUSH_RDNSS

#define EZCFG_RADVD_IF_1_DNSSL_1_SUFFIXES \
	"if1.l1." EZCFG_RADVD_SUFFIXES
#define EZCFG_RADVD_IF_1_DNSSL_1_ADV_DNSSL_LIFETIME \
	"if1.l1." EZCFG_RADVD_CONF_KEYWORD_ADV_DNSSL_LIFETIME
#define EZCFG_RADVD_IF_1_DNSSL_1_FLUSH_DNSSL \
	"if1.l1." EZCFG_RADVD_CONF_KEYWORD_FLUSH_DNSSL

#endif
