/* -*- mode: C; c-file-style: "gnu"; indent-tabs-mode: nil; -*- */
/**
 * ============================================================================
 * Project Name : ezbox configuration utilities
 * File Name    : ezcfg-emc2.h
 *
 * Description  : interface to configurate ezbox information
 *
 * Copyright (C) 2008-2014 by ezbox-project
 *
 * History      Rev       Description
 * 2011-07-07   0.1       Write it from scratch
 * ============================================================================
 */

#ifndef _EZCFG_EMC2_H_
#define _EZCFG_EMC2_H_

/* ezcfg nvram name prefix */
#define EZCFG_EMC2_NVRAM_PREFIX             "emc2."

/* ezcfg emc2 config names */
#define EZCFG_EMC2_MODULES                  "modules"
#define EZCFG_EMC2_MODPATH                  "modpath"
#define EZCFG_EMC2_RTLIB_DIR                "rtlib_dir"
#define EZCFG_EMC2_RTAPI_DEBUG              "rtapi_debug"
#define EZCFG_EMC2_INIFILE                  "inifile"

#define EZCFG_EMC2_RESTORE_DEFAULTS         "restore_defaults"

/* ezcfg emc2 latency test */
#define EZCFG_EMC2_LAT_TEST_ENABLE          "lat_test_enable"
#define EZCFG_EMC2_LAT_TEST_START           "lat_test_start"
#define EZCFG_EMC2_LAT_TEST_RESET           "lat_test_reset"
#define EZCFG_EMC2_LAT_BASE_PERIOD          "lat_base_period"
#define EZCFG_EMC2_LAT_SERVO_PERIOD         "lat_servo_period"
#define EZCFG_EMC2_LAT_SERVO_MAX_INTERVAL   "lat_servo_max_interval"
#define EZCFG_EMC2_LAT_SERVO_MAX_JITTER     "lat_servo_max_jitter"
#define EZCFG_EMC2_LAT_SERVO_LAST_INTERVAL  "lat_servo_last_interval"
#define EZCFG_EMC2_LAT_BASE_MAX_INTERVAL    "lat_base_max_interval"
#define EZCFG_EMC2_LAT_BASE_MAX_JITTER      "lat_base_max_jitter"
#define EZCFG_EMC2_LAT_BASE_LAST_INTERVAL   "lat_base_last_interval"

/* ezcfg emc2 .ini config names */
/* sections */
#define EZCFG_EMC2_CONF_SECTION_EMC         "conf_emc"
#define EZCFG_EMC2_CONF_SECTION_DISPLAY     "conf_display"
#define EZCFG_EMC2_CONF_SECTION_TASK        "conf_task"
#define EZCFG_EMC2_CONF_SECTION_AXIS        "conf_axis"
#define EZCFG_EMC2_CONF_SECTION_RS274NGC    "conf_rs274ngc"
#define EZCFG_EMC2_CONF_SECTION_EMCMOT      "conf_emcmot"
#define EZCFG_EMC2_CONF_SECTION_HAL         "conf_hal"
#define EZCFG_EMC2_CONF_SECTION_TRAJ        "conf_traj"
#define EZCFG_EMC2_CONF_SECTION_EMCIO       "conf_emcio"
/* keywords */
#define EZCFG_EMC2_CONF_KEYWORD_TYPE                "type"
#define EZCFG_EMC2_CONF_KEYWORD_WRAPPED_ROTARY      "wrapped_rotary"
#define EZCFG_EMC2_CONF_KEYWORD_UNITS               "units"
#define EZCFG_EMC2_CONF_KEYWORD_MAX_VELOCITY        "max_velocity"
#define EZCFG_EMC2_CONF_KEYWORD_MAX_ACCELERATION    "max_acceleration"
#define EZCFG_EMC2_CONF_KEYWORD_BACKLASH            "backlash"
#define EZCFG_EMC2_CONF_KEYWORD_COMP_FILE           "comp_file"
#define EZCFG_EMC2_CONF_KEYWORD_COMP_FILE_TYPE      "comp_file_type"
#define EZCFG_EMC2_CONF_KEYWORD_MIN_LIMIT           "min_limit"
#define EZCFG_EMC2_CONF_KEYWORD_MAX_LIMIT           "max_limit"
#define EZCFG_EMC2_CONF_KEYWORD_MIN_FERROR          "min_ferror"
#define EZCFG_EMC2_CONF_KEYWORD_FERROR              "ferror"
/* for homing */
#define EZCFG_EMC2_CONF_KEYWORD_HOME                "home"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_OFFSET         "home_offset"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_SEARCH_VEL     "home_search_vel"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_LATCH_VEL      "home_latch_vel"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_FINAL_VEL      "home_final_vel"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_USE_INDEX      "home_use_index"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_IGNORE_LIMITS  "home_ignore_limits"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_IS_SHARED      "home_is_shared"
#define EZCFG_EMC2_CONF_KEYWORD_HOME_SEQUENCE       "home_sequence"
#define EZCFG_EMC2_CONF_KEYWORD_VOLATILE_HOME       "volatile_home"
/* for servo system */
#define EZCFG_EMC2_CONF_KEYWORD_DEADBAND            "deadband"
#define EZCFG_EMC2_CONF_KEYWORD_BIAS                "bias"
#define EZCFG_EMC2_CONF_KEYWORD_P                   "p"
#define EZCFG_EMC2_CONF_KEYWORD_I                   "i"
#define EZCFG_EMC2_CONF_KEYWORD_D                   "d"
#define EZCFG_EMC2_CONF_KEYWORD_FF0                 "ff0"
#define EZCFG_EMC2_CONF_KEYWORD_FF1                 "ff1"
#define EZCFG_EMC2_CONF_KEYWORD_FF2                 "ff2"
#define EZCFG_EMC2_CONF_KEYWORD_OUTPUT_SCALE        "output_scale"
#define EZCFG_EMC2_CONF_KEYWORD_OUTPUT_OFFSET       "output_offset"
#define EZCFG_EMC2_CONF_KEYWORD_MAX_OUTPUT          "max_output"
#define EZCFG_EMC2_CONF_KEYWORD_INPUT_SCALE         "input_scale"
/* for stepper system */
#define EZCFG_EMC2_CONF_KEYWORD_SCALE               "scale"
#define EZCFG_EMC2_CONF_KEYWORD_STEPGEN_MAXACCEL    "stepgen_maxaccel"
#define EZCFG_EMC2_CONF_KEYWORD_STEPGEN_MAXVEL      "stepgen_maxvel"

/* [EMC] section */
#define EZCFG_EMC2_CONF_EMC_VERSION         "conf_emc_version"
#define EZCFG_EMC2_CONF_EMC_MACHINE         "conf_emc_machine"
#define EZCFG_EMC2_CONF_EMC_DEBUG           "conf_emc_debug"
#define EZCFG_EMC2_CONF_EMC_NML_FILE        "conf_emc_nml_file"
/* [DISPLAY] section */
#define EZCFG_EMC2_CONF_DISPLAY_DISPLAY           "conf_display_display"
#define EZCFG_EMC2_CONF_DISPLAY_CYCLE_TIME        "conf_display_cycle_time"
#define EZCFG_EMC2_CONF_DISPLAY_POSITION_OFFSET   "conf_display_position_offset"
#define EZCFG_EMC2_CONF_DISPLAY_POSITION_FEEDBACK "conf_display_position_feedback"
#define EZCFG_EMC2_CONF_DISPLAY_MAX_FEED_OVERRIDE "conf_display_max_feed_override"
#define EZCFG_EMC2_CONF_DISPLAY_MIN_SPINDLE_OVERRIDE \
	"conf_display_min_spindle_override"
#define EZCFG_EMC2_CONF_DISPLAY_MAX_SPINDLE_OVERRIDE \
	"conf_display_max_spindle_override"
#define EZCFG_EMC2_CONF_DISPLAY_PROGRAM_PREFIX    "conf_display_program_prefix"
#define EZCFG_EMC2_CONF_DISPLAY_INTRO_GRAPHIC     "conf_display_intro_graphic"
#define EZCFG_EMC2_CONF_DISPLAY_INTRO_TIME        "conf_display_intro_time"
#define EZCFG_EMC2_CONF_DISPLAY_HELP_FILE         "conf_display_help_file"
/* [TASK] section */
#define EZCFG_EMC2_CONF_TASK_TASK                 "conf_task_task"
#define EZCFG_EMC2_CONF_TASK_CYCLE_TIME           "conf_task_cycle_time"
/* [RS274NGC] section */
#define EZCFG_EMC2_CONF_RS274NGC_PARAMETER_FILE   "conf_rs274ngc_parameter_file"
#define EZCFG_EMC2_CONF_RS274NGC_LOG_FILE         "conf_rs274ngc_log_file"
/* [EMCMOT] section */
#define EZCFG_EMC2_CONF_EMCMOT_EMCMOT             "conf_emcmot_emcmot"
#define EZCFG_EMC2_CONF_EMCMOT_COMM_TIMEOUT       "conf_emcmot_comm_timeout"
#define EZCFG_EMC2_CONF_EMCMOT_COMM_WAIT          "conf_emcmot_comm_wait"
#define EZCFG_EMC2_CONF_EMCMOT_BASE_PERIOD        "conf_emcmot_base_period"
#define EZCFG_EMC2_CONF_EMCMOT_SERVO_PERIOD       "conf_emcmot_servo_period"
#define EZCFG_EMC2_CONF_EMCMOT_TRAJ_PERIOD        "conf_emcmot_traj_period"
/* [HAL] section */
#define EZCFG_EMC2_CONF_HAL_TWOPASS               "conf_hal_twopass"
#define EZCFG_EMC2_CONF_HAL_HALFILE               "conf_hal_halfile"
#define EZCFG_EMC2_CONF_HAL_HALFILE_NUM           "conf_hal_halfile_num"
#define EZCFG_EMC2_CONF_HAL_HALCMD                "conf_hal_halcmd"
#define EZCFG_EMC2_CONF_HAL_HALCMD_NUM            "conf_hal_halcmd_num"
#define EZCFG_EMC2_CONF_HAL_SHUTDOWN              "conf_hal_shutdown"
#define EZCFG_EMC2_CONF_HAL_HALUI                 "conf_hal_halui"
/* [HALUI] section */
#define EZCFG_EMC2_CONF_HALUI_MDI_COMMAND         "conf_halui_mdi_command"
/* [TRAJ] section */
#define EZCFG_EMC2_CONF_TRAJ_AXES                 "conf_traj_axes"
#define EZCFG_EMC2_CONF_TRAJ_COORDINATES          "conf_traj_coordinates"
#define EZCFG_EMC2_CONF_TRAJ_HOME                 "conf_traj_home"
#define EZCFG_EMC2_CONF_TRAJ_LINEAR_UNITS         "conf_traj_linear_units"
#define EZCFG_EMC2_CONF_TRAJ_ANGULAR_UNITS        "conf_traj_angular_units"
#define EZCFG_EMC2_CONF_TRAJ_CYCLE_TIME           "conf_traj_cycle_time"
#define EZCFG_EMC2_CONF_TRAJ_DEFAULT_VELOCITY     "conf_traj_default_velocity"
#define EZCFG_EMC2_CONF_TRAJ_MAX_VELOCITY         "conf_traj_max_velocity"
#define EZCFG_EMC2_CONF_TRAJ_DEFAULT_ACCELERATION "conf_traj_default_acceleration"
#define EZCFG_EMC2_CONF_TRAJ_MAX_ACCELERATION     "conf_traj_max_acceleration"
#define EZCFG_EMC2_CONF_TRAJ_NO_FORCE_HOMING      "conf_traj_no_force_homing"
/* [EMCIO] section */
#define EZCFG_EMC2_CONF_EMCIO_EMCIO                "conf_emcio_emcio"
#define EZCFG_EMC2_CONF_EMCIO_CYCLE_TIME           "conf_emcio_cycle_time"
#define EZCFG_EMC2_CONF_EMCIO_TOOL_TABLE           "conf_emcio_tool_table"
#define EZCFG_EMC2_CONF_EMCIO_TOOL_CHANGE_POSITION "conf_emcio_tool_change_position"
#define EZCFG_EMC2_CONF_EMCIO_TOOL_CHANGE_WITH_SPINDLE_ON \
	"conf_emcio_tool_change_with_spindle_on"
#define EZCFG_EMC2_CONF_EMCIO_TOOL_CHANGE_QUILL_UP \
	"conf_emcio_tool_change_quill_up"
#define EZCFG_EMC2_CONF_EMCIO_TOOL_CHANGE_AT_G30 \
	"conf_emcio_tool_change_at_g30"
#define EZCFG_EMC2_CONF_EMCIO_RANDOM_TOOLCHANGER \
	"conf_emcio_random_toolchanger"
/* [AXIS_0] section */
#define EZCFG_EMC2_CONF_AXIS_0_TYPE                "conf_axis_0_type"
#define EZCFG_EMC2_CONF_AXIS_0_HOME                "conf_axis_0_home"
#define EZCFG_EMC2_CONF_AXIS_0_MAX_VELOCITY        "conf_axis_0_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_0_MAX_ACCELERATION    "conf_axis_0_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_0_STEPGEN_MAXACCEL    "conf_axis_0_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_0_BACKLASH            "conf_axis_0_backlash"
#define EZCFG_EMC2_CONF_AXIS_0_SCALE               "conf_axis_0_scale"
#define EZCFG_EMC2_CONF_AXIS_0_OUTPUT_SCALE         "conf_axis_0_output_scale"
#define EZCFG_EMC2_CONF_AXIS_0_MIN_LIMIT           "conf_axis_0_min_limit"
#define EZCFG_EMC2_CONF_AXIS_0_MAX_LIMIT           "conf_axis_0_max_limit"
#define EZCFG_EMC2_CONF_AXIS_0_FERROR              "conf_axis_0_ferror"
#define EZCFG_EMC2_CONF_AXIS_0_MIN_FERROR          "conf_axis_0_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_0_HOME_OFFSET         "conf_axis_0_home_offset"
#define EZCFG_EMC2_CONF_AXIS_0_HOME_SEARCH_VEL     "conf_axis_0_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_0_HOME_LATCH_VEL      "conf_axis_0_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_0_HOME_FINAL_VEL      "conf_axis_0_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_0_HOME_USE_INDEX      "conf_axis_0_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_0_HOME_IGNORE_LIMITS  "conf_axis_0_home_ignore_limits"
/* [AXIS_1] section */
#define EZCFG_EMC2_CONF_AXIS_1_TYPE                "conf_axis_1_type"
#define EZCFG_EMC2_CONF_AXIS_1_HOME                "conf_axis_1_home"
#define EZCFG_EMC2_CONF_AXIS_1_MAX_VELOCITY        "conf_axis_1_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_1_MAX_ACCELERATION    "conf_axis_1_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_1_STEPGEN_MAXACCEL    "conf_axis_1_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_1_BACKLASH            "conf_axis_1_backlash"
#define EZCFG_EMC2_CONF_AXIS_1_SCALE               "conf_axis_1_scale"
#define EZCFG_EMC2_CONF_AXIS_1_OUTPUT_SCALE         "conf_axis_1_output_scale"
#define EZCFG_EMC2_CONF_AXIS_1_MIN_LIMIT           "conf_axis_1_min_limit"
#define EZCFG_EMC2_CONF_AXIS_1_MAX_LIMIT           "conf_axis_1_max_limit"
#define EZCFG_EMC2_CONF_AXIS_1_FERROR              "conf_axis_1_ferror"
#define EZCFG_EMC2_CONF_AXIS_1_MIN_FERROR          "conf_axis_1_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_1_HOME_OFFSET         "conf_axis_1_home_offset"
#define EZCFG_EMC2_CONF_AXIS_1_HOME_SEARCH_VEL     "conf_axis_1_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_1_HOME_LATCH_VEL      "conf_axis_1_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_1_HOME_FINAL_VEL      "conf_axis_1_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_1_HOME_USE_INDEX      "conf_axis_1_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_1_HOME_IGNORE_LIMITS  "conf_axis_1_home_ignore_limits"
/* [AXIS_2] section */
#define EZCFG_EMC2_CONF_AXIS_2_TYPE                "conf_axis_2_type"
#define EZCFG_EMC2_CONF_AXIS_2_HOME                "conf_axis_2_home"
#define EZCFG_EMC2_CONF_AXIS_2_MAX_VELOCITY        "conf_axis_2_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_2_MAX_ACCELERATION    "conf_axis_2_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_2_STEPGEN_MAXACCEL    "conf_axis_2_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_2_BACKLASH            "conf_axis_2_backlash"
#define EZCFG_EMC2_CONF_AXIS_2_SCALE               "conf_axis_2_scale"
#define EZCFG_EMC2_CONF_AXIS_2_OUTPUT_SCALE         "conf_axis_2_output_scale"
#define EZCFG_EMC2_CONF_AXIS_2_MIN_LIMIT           "conf_axis_2_min_limit"
#define EZCFG_EMC2_CONF_AXIS_2_MAX_LIMIT           "conf_axis_2_max_limit"
#define EZCFG_EMC2_CONF_AXIS_2_FERROR              "conf_axis_2_ferror"
#define EZCFG_EMC2_CONF_AXIS_2_MIN_FERROR          "conf_axis_2_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_2_HOME_OFFSET         "conf_axis_2_home_offset"
#define EZCFG_EMC2_CONF_AXIS_2_HOME_SEARCH_VEL     "conf_axis_2_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_2_HOME_LATCH_VEL      "conf_axis_2_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_2_HOME_FINAL_VEL      "conf_axis_2_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_2_HOME_USE_INDEX      "conf_axis_2_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_2_HOME_IGNORE_LIMITS  "conf_axis_2_home_ignore_limits"
/* [AXIS_3] section */
#define EZCFG_EMC2_CONF_AXIS_3_TYPE                "conf_axis_3_type"
#define EZCFG_EMC2_CONF_AXIS_3_HOME                "conf_axis_3_home"
#define EZCFG_EMC2_CONF_AXIS_3_MAX_VELOCITY        "conf_axis_3_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_3_MAX_ACCELERATION    "conf_axis_3_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_3_STEPGEN_MAXACCEL    "conf_axis_3_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_3_BACKLASH            "conf_axis_3_backlash"
#define EZCFG_EMC2_CONF_AXIS_3_SCALE               "conf_axis_3_scale"
#define EZCFG_EMC2_CONF_AXIS_3_OUTPUT_SCALE         "conf_axis_3_output_scale"
#define EZCFG_EMC2_CONF_AXIS_3_MIN_LIMIT           "conf_axis_3_min_limit"
#define EZCFG_EMC2_CONF_AXIS_3_MAX_LIMIT           "conf_axis_3_max_limit"
#define EZCFG_EMC2_CONF_AXIS_3_FERROR              "conf_axis_3_ferror"
#define EZCFG_EMC2_CONF_AXIS_3_MIN_FERROR          "conf_axis_3_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_3_HOME_OFFSET         "conf_axis_3_home_offset"
#define EZCFG_EMC2_CONF_AXIS_3_HOME_SEARCH_VEL     "conf_axis_3_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_3_HOME_LATCH_VEL      "conf_axis_3_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_3_HOME_FINAL_VEL      "conf_axis_3_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_3_HOME_USE_INDEX      "conf_axis_3_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_3_HOME_IGNORE_LIMITS  "conf_axis_3_home_ignore_limits"
/* [AXIS_4] section */
#define EZCFG_EMC2_CONF_AXIS_4_TYPE                "conf_axis_4_type"
#define EZCFG_EMC2_CONF_AXIS_4_HOME                "conf_axis_4_home"
#define EZCFG_EMC2_CONF_AXIS_4_MAX_VELOCITY        "conf_axis_4_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_4_MAX_ACCELERATION    "conf_axis_4_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_4_STEPGEN_MAXACCEL    "conf_axis_4_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_4_BACKLASH            "conf_axis_4_backlash"
#define EZCFG_EMC2_CONF_AXIS_4_SCALE               "conf_axis_4_scale"
#define EZCFG_EMC2_CONF_AXIS_4_OUTPUT_SCALE         "conf_axis_4_output_scale"
#define EZCFG_EMC2_CONF_AXIS_4_MIN_LIMIT           "conf_axis_4_min_limit"
#define EZCFG_EMC2_CONF_AXIS_4_MAX_LIMIT           "conf_axis_4_max_limit"
#define EZCFG_EMC2_CONF_AXIS_4_FERROR              "conf_axis_4_ferror"
#define EZCFG_EMC2_CONF_AXIS_4_MIN_FERROR          "conf_axis_4_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_4_HOME_OFFSET         "conf_axis_4_home_offset"
#define EZCFG_EMC2_CONF_AXIS_4_HOME_SEARCH_VEL     "conf_axis_4_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_4_HOME_LATCH_VEL      "conf_axis_4_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_4_HOME_FINAL_VEL      "conf_axis_4_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_4_HOME_USE_INDEX      "conf_axis_4_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_4_HOME_IGNORE_LIMITS  "conf_axis_4_home_ignore_limits"
/* [AXIS_5] section */
#define EZCFG_EMC2_CONF_AXIS_5_TYPE                "conf_axis_5_type"
#define EZCFG_EMC2_CONF_AXIS_5_HOME                "conf_axis_5_home"
#define EZCFG_EMC2_CONF_AXIS_5_MAX_VELOCITY        "conf_axis_5_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_5_MAX_ACCELERATION    "conf_axis_5_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_5_STEPGEN_MAXACCEL    "conf_axis_5_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_5_BACKLASH            "conf_axis_5_backlash"
#define EZCFG_EMC2_CONF_AXIS_5_SCALE               "conf_axis_5_scale"
#define EZCFG_EMC2_CONF_AXIS_5_OUTPUT_SCALE         "conf_axis_5_output_scale"
#define EZCFG_EMC2_CONF_AXIS_5_MIN_LIMIT           "conf_axis_5_min_limit"
#define EZCFG_EMC2_CONF_AXIS_5_MAX_LIMIT           "conf_axis_5_max_limit"
#define EZCFG_EMC2_CONF_AXIS_5_FERROR              "conf_axis_5_ferror"
#define EZCFG_EMC2_CONF_AXIS_5_MIN_FERROR          "conf_axis_5_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_5_HOME_OFFSET         "conf_axis_5_home_offset"
#define EZCFG_EMC2_CONF_AXIS_5_HOME_SEARCH_VEL     "conf_axis_5_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_5_HOME_LATCH_VEL      "conf_axis_5_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_5_HOME_FINAL_VEL      "conf_axis_5_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_5_HOME_USE_INDEX      "conf_axis_5_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_5_HOME_IGNORE_LIMITS  "conf_axis_5_home_ignore_limits"
/* [AXIS_6] section */
#define EZCFG_EMC2_CONF_AXIS_6_TYPE                "conf_axis_6_type"
#define EZCFG_EMC2_CONF_AXIS_6_HOME                "conf_axis_6_home"
#define EZCFG_EMC2_CONF_AXIS_6_MAX_VELOCITY        "conf_axis_6_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_6_MAX_ACCELERATION    "conf_axis_6_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_6_STEPGEN_MAXACCEL    "conf_axis_6_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_6_BACKLASH            "conf_axis_6_backlash"
#define EZCFG_EMC2_CONF_AXIS_6_SCALE               "conf_axis_6_scale"
#define EZCFG_EMC2_CONF_AXIS_6_OUTPUT_SCALE         "conf_axis_6_output_scale"
#define EZCFG_EMC2_CONF_AXIS_6_MIN_LIMIT           "conf_axis_6_min_limit"
#define EZCFG_EMC2_CONF_AXIS_6_MAX_LIMIT           "conf_axis_6_max_limit"
#define EZCFG_EMC2_CONF_AXIS_6_FERROR              "conf_axis_6_ferror"
#define EZCFG_EMC2_CONF_AXIS_6_MIN_FERROR          "conf_axis_6_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_6_HOME_OFFSET         "conf_axis_6_home_offset"
#define EZCFG_EMC2_CONF_AXIS_6_HOME_SEARCH_VEL     "conf_axis_6_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_6_HOME_LATCH_VEL      "conf_axis_6_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_6_HOME_FINAL_VEL      "conf_axis_6_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_6_HOME_USE_INDEX      "conf_axis_6_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_6_HOME_IGNORE_LIMITS  "conf_axis_6_home_ignore_limits"
/* [AXIS_7] section */
#define EZCFG_EMC2_CONF_AXIS_7_TYPE                "conf_axis_7_type"
#define EZCFG_EMC2_CONF_AXIS_7_HOME                "conf_axis_7_home"
#define EZCFG_EMC2_CONF_AXIS_7_MAX_VELOCITY        "conf_axis_7_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_7_MAX_ACCELERATION    "conf_axis_7_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_7_STEPGEN_MAXACCEL    "conf_axis_7_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_7_BACKLASH            "conf_axis_7_backlash"
#define EZCFG_EMC2_CONF_AXIS_7_SCALE               "conf_axis_7_scale"
#define EZCFG_EMC2_CONF_AXIS_7_OUTPUT_SCALE         "conf_axis_7_output_scale"
#define EZCFG_EMC2_CONF_AXIS_7_MIN_LIMIT           "conf_axis_7_min_limit"
#define EZCFG_EMC2_CONF_AXIS_7_MAX_LIMIT           "conf_axis_7_max_limit"
#define EZCFG_EMC2_CONF_AXIS_7_FERROR              "conf_axis_7_ferror"
#define EZCFG_EMC2_CONF_AXIS_7_MIN_FERROR          "conf_axis_7_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_7_HOME_OFFSET         "conf_axis_7_home_offset"
#define EZCFG_EMC2_CONF_AXIS_7_HOME_SEARCH_VEL     "conf_axis_7_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_7_HOME_LATCH_VEL      "conf_axis_7_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_7_HOME_FINAL_VEL      "conf_axis_7_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_7_HOME_USE_INDEX      "conf_axis_7_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_7_HOME_IGNORE_LIMITS  "conf_axis_7_home_ignore_limits"
/* [AXIS_8] section */
#define EZCFG_EMC2_CONF_AXIS_8_TYPE                "conf_axis_8_type"
#define EZCFG_EMC2_CONF_AXIS_8_HOME                "conf_axis_8_home"
#define EZCFG_EMC2_CONF_AXIS_8_MAX_VELOCITY        "conf_axis_8_max_velocity"
#define EZCFG_EMC2_CONF_AXIS_8_MAX_ACCELERATION    "conf_axis_8_max_acceleration"
#define EZCFG_EMC2_CONF_AXIS_8_STEPGEN_MAXACCEL    "conf_axis_8_stepgen_maxaccel"
#define EZCFG_EMC2_CONF_AXIS_8_BACKLASH            "conf_axis_8_backlash"
#define EZCFG_EMC2_CONF_AXIS_8_SCALE               "conf_axis_8_scale"
#define EZCFG_EMC2_CONF_AXIS_8_OUTPUT_SCALE         "conf_axis_8_output_scale"
#define EZCFG_EMC2_CONF_AXIS_8_MIN_LIMIT           "conf_axis_8_min_limit"
#define EZCFG_EMC2_CONF_AXIS_8_MAX_LIMIT           "conf_axis_8_max_limit"
#define EZCFG_EMC2_CONF_AXIS_8_FERROR              "conf_axis_8_ferror"
#define EZCFG_EMC2_CONF_AXIS_8_MIN_FERROR          "conf_axis_8_min_ferror"
#define EZCFG_EMC2_CONF_AXIS_8_HOME_OFFSET         "conf_axis_8_home_offset"
#define EZCFG_EMC2_CONF_AXIS_8_HOME_SEARCH_VEL     "conf_axis_8_home_search_vel"
#define EZCFG_EMC2_CONF_AXIS_8_HOME_LATCH_VEL      "conf_axis_8_home_latch_vel"
#define EZCFG_EMC2_CONF_AXIS_8_HOME_FINAL_VEL      "conf_axis_8_home_final_vel"
#define EZCFG_EMC2_CONF_AXIS_8_HOME_USE_INDEX      "conf_axis_8_home_use_index"
#define EZCFG_EMC2_CONF_AXIS_8_HOME_IGNORE_LIMITS  "conf_axis_8_home_ignore_limits"

/* emcrsh config */
#define EZCFG_EMC2_EMCRSH_PORT                     "emcrsh_port"
#define EZCFG_EMC2_EMCRSH_NAME                     "emcrsh_name"
#define EZCFG_EMC2_EMCRSH_CONNECTPW                "emcrsh_connectpw"
#define EZCFG_EMC2_EMCRSH_ENABLEPW                 "emcrsh_enablepw"
#define EZCFG_EMC2_EMCRSH_SESSIONS                 "emcrsh_sessions"
//#define EZCFG_EMC2_EMCRSH_PATH                     "emcrsh_path"
#define EZCFG_EMC2_EMCRSH_PATH                     EZCFG_EMC2_CONF_DISPLAY_PROGRAM_PREFIX

#endif
